// Polski Trener — данные карточек
// Редактируйте вопросы здесь. Формат:
//   q: вопрос, a: ответ (через / для альтернатив), hint: подсказка, rule: правило
var T=[
{id:"conj",icon:"\u{1F504}",title:"Спряжение глаголов",color:"#2d6a4f",cards:[
{q:"pracować → Ola i Daniel ... (oni)",a:"pracują",hint:"-ują (I спр.)",rule:"I спряжение: -ować → -uj-\n\nja → pracuję\nty → pracujesz\non → pracuje\nmy → pracujemy\nwy → pracujecie\noni → pracują\n\nТак же: kupować → kupuję, budować → buduję"},
{q:"chodzić → Często ... po górach (ja)",a:"chodzę",hint:"-ę (II спр.)",rule:"II спряжение (-ę, -isz): глаголы на -ić.\n\nja → chodzę\nty → chodzisz\non → chodzi\nmy → chodzimy\nwy → chodzicie\noni → chodzą\n\nЧередование dz/dzi в 1 ед. и 3 мн."},
{q:"zamawiać → Oni ... jedzenie",a:"zamawiają",hint:"-ają",rule:"I спр.: глаголы на -ać, основа -aj-\n\nja → zamawiam\nty → zamawiasz\non → zamawia\noni → zamawiają\n\nТак же: wysyłać → wysyłają, czekać → czekają"},
{q:"wiedzieć → Oni nie ... jak dojść",a:"wiedzą",hint:"неправильный",rule:"wiedzieć — неправильный:\n\nja → wiem\nty → wiesz\non → wie\nmy → wiemy\noni → wiedzą\n\n3 мн.ч. = wiedzą (не wiezą!)"},
{q:"mieć → 80% Polaków ... zwierzę",a:"ma",hint:"% + ед.ч. глагола",rule:"Процент/большинство → глагол в 3 ед.ч.:\n\n80% Polaków ma... (не mają!)\nWiększość studentów uczy się...\nPołowa ludzi nie wie..."},
{q:"pisać → Co ty ...? (ty)",a:"piszesz",hint:"s→sz, I спр.",rule:"pisać — I спр. с чередованием s→sz:\n\nja → piszę\nty → piszesz\non → pisze\noni → piszą\n\nТак же: kazać → każę, tańczyć → tańczę"},
{q:"jeść → Dzieci ... obiad o 13:00",a:"jedzą",hint:"неправильный",rule:"jeść — неправильный:\n\nja → jem\nty → jesz\non → je\nmy → jemy\noni → jedzą"},
{q:"robić → Co ... w weekend? (wy)",a:"robicie",hint:"-icie (II спр.)",rule:"robić — II спр.:\n\nja → robię\nty → robisz\non → robi\nwy → robicie\noni → robią"},
{q:"umieć → Ona ... dobrze gotować",a:"umie",hint:"-eć → -ie",rule:"umieć — II спр.:\n\nja → umiem\nty → umiesz\non → umie\noni → umieją\n\nТак же: rozumieć → rozumiem"},
{q:"musieć → ... iść do lekarza (ja)",a:"muszę",hint:"s→sz",rule:"musieć — II спр. с чередованием:\n\nja → muszę\nty → musisz\non → musi\noni → muszą\n\nЧередование s→sz в 1 ед. и 3 мн."},
{q:"móc → Czy ... mi pomóc? (ty)",a:"możesz",hint:"I спр., неправильный",rule:"móc — неправильный:\n\nja → mogę\nty → możesz\non → może\nmy → możemy\noni → mogą\n\nЧередование g→ż: mogę/możesz"},
{q:"lubić → Bardzo ... czekoladę (ja)",a:"lubię",hint:"II спр. -ię",rule:"lubić — II спр.:\n\nja → lubię\nty → lubisz\non → lubi\noni → lubią\n\nТак же: robić, mówić, prosić"},
{q:"spać → Kot ... na kanapie (on)",a:"śpi",hint:"неправильный, II спр.",rule:"spać — неправильный, II спр.:\n\nja → śpię\nty → śpisz\non → śpi\nmy → śpimy\noni → śpią\n\nЧередование sp→śp"},
{q:"brać → Ile ... za lekcję? (ty)",a:"bierzesz",hint:"I спр., чередование",rule:"brać — I спр. с чередованием:\n\nja → biorę\nty → bierzesz\non → bierze\nmy → bierzemy\noni → biorą\n\nВнимание: biorę/biorą (1,3), bierzesz (ост.)"},
{q:"myć → Mama ... naczynia (ona)",a:"myje",hint:"I спр., -yć → -yje",rule:"myć — I спр.:\n\nja → myję\nty → myjesz\non → myje\noni → myją\n\nТак же: żyć → żyję, szyć → szyję"},
{q:"czytać → Ania ... książkę (ona)",a:"czyta",hint:"I спр. -ać → -a",rule:"I спр. -ać → -a- :\n\nja → czytam\nty → czytasz\non → czyta\nmy → czytamy\noni → czytają\n\nТак же: słuchać, kochać, grać, pytać"},
{q:"uczyć się → My ... polskiego (my)",a:"uczymy się",hint:"II спр. + się",rule:"uczyć się — II спр.:\n\nja → uczę się\nty → uczysz się\non → uczy się\nmy → uczymy się\noni → uczą się\n\nЧередование cz/cz в основе"},
{q:"woleć → ... herbatę niż kawę (ja)",a:"wolę",hint:"II спр. -eć → -ę",rule:"woleć — II спр.:\n\nja → wolę\nty → wolisz\non → woli\nmy → wolimy\noni → wolą\n\nwoleć = предпочитать\nWolę X niż Y."}
]},

{id:"znac",icon:"\u{1F9E0}",title:"znać vs wiedzieć",color:"#7b2cbf",cards:[
{q:"Julia ... język hiszpański.\n(a) zna  (b) wie",a:"zna",hint:"znać + сущ.",rule:"znać = знать кого/что (+ существительное):\n• Znam język polski.\n• Znasz tę osobę?\n\nwiedzieć = знать (+ придаточное: że, jak, co):\n• Wiem, że to prawda.\n\nТест: «кого/что?» → znać. «Что? как?» → wiedzieć."},
{q:"Oni nie ..., jak dojść do parku.\n(a) znają  (b) wiedzą",a:"wiedzą",hint:"wiedzieć + jak",rule:"wiedzieć + придаточное (jak, że, co, gdzie).\n\nNie wiedzą, jak dojść...\nWiem, że masz rację.\n\nznać — только с дополнением: Znam tę drogę."},
{q:"... pan tę restaurację?\n(a) Zna  (b) Wie",a:"Zna",hint:"знать что → znać",rule:"znać + сущ. в Biernik.\n«Знаете этот ресторан?» → znać.\n\nZna pan tę restaurację?"},
{q:"Nie ..., o której zaczyna się film.\n(a) znam  (b) wiem",a:"wiem",hint:"информация → wiedzieć",rule:"wiedzieć = информация, факт.\n\nNie wiem, o której... / Nie wiem, kiedy... / Nie wiem, dlaczego..."},
{q:"Czy ... swoich sąsiadów?\n(a) znasz  (b) wiesz",a:"znasz",hint:"знать кого → znać",rule:"znać + лицо (кого?)\n\nZnasz sąsiadów? = Знаешь соседей?\nОбъект — люди → znać."},
{q:"Nie ..., ile to kosztuje.\n(a) znam  (b) wiem",a:"wiem",hint:"wiedzieć + ile",rule:"wiedzieć перед вопросительными словами:\n\nNie wiem, ile kosztuje. (сколько)\nNie wiem, co to znaczy. (что)\nNie wiem, gdzie to jest. (где)"},
{q:"Dobrze ... ten film, widziałem go 3 razy.\n(a) znam  (b) wiem",a:"znam",hint:"знакомство → znać",rule:"znać = быть знакомым с чем-то.\n\nZnam ten film. = Знаком с фильмом.\nZnam to miejsce.\n\nЗнание через опыт → znać."},
{q:"Nie ..., czy ona przyjdzie.\n(a) znam  (b) wiem",a:"wiem",hint:"wiedzieć + czy",rule:"wiedzieć + czy (ли):\n\nNie wiem, czy przyjdzie.\nNie wiem, czy to prawda.\n\nczy = вводит косвенный вопрос → wiedzieć."},
{q:"... dobrze tę okolicę, mieszkam tu 10 lat.\n(a) Znam  (b) Wiem",a:"Znam",hint:"знать место → znać",rule:"znać + место (как объект знакомства):\n\nZnam tę okolicę. (знаю эту местность)\nZnam Kraków bardzo dobrze.\n\nНо: Wiem, gdzie jest Kraków. (информация)"},
{q:"Czy ... , kto to napisał?\n(a) znasz  (b) wiesz",a:"wiesz",hint:"wiedzieć + kto",rule:"wiedzieć + kto/co/jak/gdzie/kiedy:\n\nCzy wiesz, kto to napisał?\nCzy wiesz, co się stało?\n\nВопросительное слово → wiedzieć."},
{q:"Nie ... tego słowa, co ono znaczy?\n(a) znam  (b) wiem",a:"znam",hint:"słowo = объект → znać",rule:"znać + конкретный объект:\n\nNie znam tego słowa. (не знаю это слово)\nNie znam tej piosenki. (не знаю эту песню)\n\nНо: Nie wiem, co to słowo znaczy. (информация)"},
{q:"... swoją wartość i nie dam się wykorzystać.\n(a) Znam  (b) Wiem",a:"Znam",hint:"znać = осознавать",rule:"znać + абстрактное понятие (как объект):\n\nZnam swoją wartość. (знаю свою ценность)\nZnam swoje prawa.\nZnam ryzyko.\n\nОбъект → znać."},
{q:"Nie ..., jak to powiedzieć po polsku.\n(a) znam  (b) wiem",a:"wiem",hint:"wiedzieć + jak",rule:"wiedzieć + jak (как):\n\nNie wiem, jak to powiedzieć.\nNie wiem, jak to zrobić.\n\njak = вопросительное слово → wiedzieć."},
{q:"On dobrze ... swój fach.\n(a) zna  (b) wie",a:"zna",hint:"fach = объект → znać",rule:"znać + область/умение как объект:\n\nZna swój fach. (знает своё ремесло)\nZna się na rzeczy. (разбирается)\n\nОбъект (сущ.) → znać."},
{q:"Nikt nie ..., co będzie jutro.\n(a) zna  (b) wie",a:"wie",hint:"wiedzieć + co",rule:"wiedzieć + co:\n\nNikt nie wie, co będzie jutro.\nNikt nie wie, co się stanie.\n\nco = вопросительное → wiedzieć."}
]},

{id:"narz",icon:"\u{1F527}",title:"Творительный (Narzędnik)",color:"#e36414",cards:[
{q:"Mój brat jest ... ... (początkujący programista)",a:"początkującym programistą",hint:"być + Narz.",rule:"Narzędnik после być:\n\nПрилаг.: -y → -ym\nСущ. муж. на -a: -a → -ą\n\npoczątkujący → początkującym\nprogramista → programistą"},
{q:"Do pracy jadę ... (hulajnoga)",a:"hulajnogą",hint:"-a → -ą",rule:"Narzędnik транспорта (без предлога):\n\nЖен. -a → -ą: hulajnogą, taksówką\nМуж. + -em: tramwajem, autobusem"},
{q:"Latte z ... ... (mleko roślinne)",a:"mlekiem roślinnym",hint:"z + Narz.",rule:"z + Narzędnik = с чем\n\nСр.: -o → -em (mleko → mlekiem)\nПрилаг. ср.: -e → -ym (roślinne → roślinnym)"},
{q:"Jeździlibyście ... (tramwaj)",a:"tramwajem",hint:"транспорт",rule:"Транспорт в Narzędnik:\n\ntramwaj → tramwajem\nautobus → autobusem\nsamochód → samochodem"},
{q:"Interesuję się ... (historia)",a:"historią",hint:"interesować się + Narz.",rule:"interesować się + Narzędnik:\n\nhistoria → historią\ngeografia → geografią\n\nТакже: zajmować się, opiekować się + Narz."},
{q:"Ona jest ... ... (dobra nauczycielka)",a:"dobrą nauczycielką",hint:"жен. Narz.",rule:"Narzędnik жен.:\n\nПрилаг.: -a → -ą (dobra → dobrą)\nСущ. -ka → -ką (nauczycielka → nauczycielką)"},
{q:"Rozmawiam z moim ... (brat)",a:"bratem",hint:"z + муж. -em",rule:"z + Narzędnik муж.:\n\nbrat → bratem\nojciec → ojcem\nprzyjaciel → przyjacielem"},
{q:"Pojechaliśmy tam ... (samolot)",a:"samolotem",hint:"-em",rule:"Транспорт муж.: + -em\n\nsamolot → samolotem\nstatek → statkiem\npociąg → pociągiem"},
{q:"Przed ... (szkoła) stoi autobus",a:"szkołą",hint:"przed + Narz.",rule:"przed + Narzędnik = перед чем:\n\nprzed szkołą, przed domem, przed obiadem\n\nЖен. -a → -ą, Муж. + -em, Ср. -o → -em"},
{q:"Między ... a ... (dom, park)",a:"domem a parkiem",hint:"między + Narz. a Narz.",rule:"między + Narz. a + Narz. = между:\n\nmiędzy domem a parkiem\nmiędzy pracą a domem\n\nМуж.: + -em"},
{q:"Martwię się ... (zdrowie)",a:"zdrowiem",hint:"-ie → -iem",rule:"martwić się + Narzędnik = волноваться о:\n\nzdrowie → zdrowiem\ndziecko → dzieckiem\n\nСр. на -ie: -ie → -iem"},
{q:"Jest ... ... (znany aktor)",a:"znanym aktorem",hint:"być + муж. Narz.",rule:"być + Narzędnik (муж.):\n\nПрилаг.: -y → -ym (znany → znanym)\nСущ. муж.: + -em (aktor → aktorem)\n\nJest znanym aktorem. Jest dobrym lekarzem."},
{q:"Idę na spotkanie z ... (koleżanka Ania)",a:"koleżanką Anią",hint:"z + жен. Narz.",rule:"Имена собственные тоже склоняются:\n\nAnia → Anią, Kasia → Kasią\nkoleżanka → koleżanką\n\nz koleżanką Anią"},
{q:"Kroję chleb ... (nóż)",a:"nożem",hint:"инструмент в Narz.",rule:"Инструмент (чем?) = Narzędnik без предлога:\n\nnóż → nożem\nwidelec → widelcem\nołówek → ołówkiem\n\nKroję nożem. Piszę ołówkiem."},
{q:"Cieszę się ... wynikiem (dobry)",a:"dobrym",hint:"cieszyć się + Narz.",rule:"cieszyć się + Narz. = радоваться чему:\n\ndobry → dobrym\nwynik → wynikiem\n\nCieszę się dobrym wynikiem.\nТакже: cieszyć się życiem, pogodą"},
{q:"Zajmuję się ... (dziecko, мн.ч.)",a:"dziećmi",hint:"мн.ч. Narz. неправ.",rule:"Мн.ч. Narzędnik — неправильные:\n\ndzieci → dziećmi\nludzie → ludźmi\nkonie → końmi\n\nОбычное мн.ч.: + -ami (kotami, psami)"}
]},

{id:"dop",icon:"\u{1F4C9}",title:"Родительный (Dopełniacz)",color:"#d62828",cards:[
{q:"Nie lubię ... ... (mocna kawa)",a:"mocnej kawy",hint:"nie + Dop.",rule:"Dopełniacz после отрицания:\n\nЖен. прилаг.: -a → -ej (mocna → mocnej)\nЖен. сущ.: -a → -y (kawa → kawy)\n\nNie lubię mocnej kawy. Nie mam czasu."},
{q:"brakiem ... na bilety (pieniądze)",a:"pieniędzy",hint:"мн.ч. Dop.",rule:"Dopełniacz мн.ч. неправильные:\n\npieniądze → pieniędzy\ndzieci → dzieci\nludzie → ludzi"},
{q:"Od ... pożyczyłeś? (kto)",a:"kogo",hint:"od + Dop.",rule:"od + Dopełniacz.\n\nkto → kogo\nco → czego\non → niego (после предлога)"},
{q:"Z powodu ... (choroba)",a:"choroby",hint:"z powodu + Dop.",rule:"z powodu + Dop. = из-за (форм.)\n\nchoroba → choroby\ndeszcz → deszczu\n\nСравни: przez + Biernik (разг.)"},
{q:"Nie ma ... ... (troje studentów)",a:"trojga studentów",hint:"troje → trojga",rule:"Собирательные в Dop.:\n\ndwoje → dwojga\ntroje → trojga\nczworo → czworga"},
{q:"Szukam ... ... (nowy telefon)",a:"nowego telefonu",hint:"szukać + Dop.",rule:"szukać + Dop.:\n\nМуж. прилаг.: -y → -ego (nowy → nowego)\nМуж. неодуш.: -∅ → -u (telefon → telefonu)\n\nТакже: potrzebować, unikać, bać się + Dop."},
{q:"Do ... jedzie autobus? (dworzec)",a:"dworca",hint:"-ec → -ca",rule:"do + Dop. = до, к\n\ndworzec → dworca\nojciec → ojca\nchłopiec → chłopca"},
{q:"Nie ma tu ... (woda)",a:"wody",hint:"nie ma + Dop.",rule:"nie ma + Dop. = нет\n\nwoda → wody\nchleb → chleba\nmleko → mleka"},
{q:"Kupiłem butelkę ... (sok pomarańczowy)",a:"soku pomarańczowego",hint:"количество + Dop.",rule:"Количество + Dop.:\n\nsok → soku, pomarańczowy → pomarańczowego\n\nbutelkę soku, szklankę mleka, kilogram cukru"},
{q:"Bez ... (parasol) nie wychodź!",a:"parasola",hint:"bez + Dop.",rule:"bez + Dop. = без\n\nparasol → parasola\ntelefon → telefonu\n\nBez parasola, bez pieniędzy, bez pracy"},
{q:"Naprzeciwko ... (kościół) jest apteka",a:"kościoła",hint:"напротив + Dop.",rule:"naprzeciwko + Dop. = напротив\n\nkościół → kościoła\n\nТак же: obok + Dop., koło + Dop., blisko + Dop."},
{q:"Podczas ... (spotkanie) nie używajcie telefonów",a:"spotkania",hint:"podczas + Dop.",rule:"podczas + Dop. = во время\n\nСр. род: -e → -a (spotkanie → spotkania)\n\npodczas spotkania, podczas lekcji, podczas przerwy"},
{q:"Nie piję ... (alkohol)",a:"alkoholu",hint:"не пить чего → Dop.",rule:"Отрицание + Dop.:\n\nalkohol → alkoholu\nkawa → kawy\n\nНо: Piję kawę. (утверд. → Biernik)"},
{q:"To jest dom ... ... (moja babcia)",a:"mojej babci",hint:"чей? → Dop.",rule:"Dopełniacz принадлежности (чей?):\n\nЖен. прилаг.: -a → -ej (moja → mojej)\nЖен. на -ia: -ia → -i (babcia → babci)"},
{q:"Boisz się ... (pająk, мн.ч.)?",a:"pająków",hint:"bać się + Dop. мн.",rule:"bać się + Dop. = бояться чего:\n\nМн. муж. одуш.: -ów (pająk → pająków)\n\nbać się pająków, psów, egzaminów"},
{q:"Potrzebuję ... (pomoc)",a:"pomocy",hint:"-c → -cy",rule:"potrzebować + Dop.:\n\npomoc → pomocy\nnoc → nocy\nrzecz → rzeczy\n\nЖен. на согласную: + -y/-i"},
{q:"Ile ... (osoba) przyszło na spotkanie?",a:"osób",hint:"ile + Dop. мн.",rule:"ile + Dop. мн.:\n\nosoba → osób (выпадение -o-)\nksiążka → książek\nstudent → studentów\n\nile osób, ile książek, ile studentów"}
]},

{id:"miej",icon:"\u{1F4CD}",title:"Местный (Miejscownik)",color:"#0077b6",cards:[
{q:"Mieszkamy w ... (Szwecja)",a:"Szwecji",hint:"-ja → -ji",rule:"Miejscownik после w, na, o, po, przy.\n\nЖен. -ja → -ji: Szwecja → Szwecji\nЖен. -ka → -ce: Polska → Polsce"},
{q:"Byłam w ... ... (nowa kawiarnia)",a:"nowej kawiarni",hint:"-a → -ej, -nia → -ni",rule:"Miejscownik жен.:\n\nПрилаг.: -a → -ej\nСущ. -nia → -ni (kawiarnia → kawiarni)\n-ka → -ce (apteka → aptece)\n-a → -e (szkoła → szkole)"},
{q:"Parki w moim ... (miasto)",a:"mieście",hint:"st → ści",rule:"Miejscownik ср. — чередования:\n\nmiasto → mieście (st → ści)\nmorze → morzu\npiwo → piwie (w → wi)"},
{q:"Spotkanie o ... ... (08:30)",a:"ósmej trzydzieści",hint:"o + порядк. в Miej.",rule:"Время: o + порядковое в Miej. (жен.):\n\no ósmej = в 8:00\no wpół do dziewiątej = в 8:30\no pierwszej, o drugiej, o trzeciej..."},
{q:"Rozmawialiśmy o ... (pogoda)",a:"pogodzie",hint:"-da → -dzie",rule:"o + Miej. = о чём-то\n\n-da → -dzie: pogoda → pogodzie\n-ta → -cie: robota → robocie\n-ra → -rze: literatura → literaturze"},
{q:"Mieszkam na ... ... (trzecie piętro)",a:"trzecim piętrze",hint:"ср. Miej.",rule:"na + Miej.:\n\nСр. прилаг.: -ie → -im\nСр. сущ.: -o → -e (piętro → piętrze)\n\nna trzecim piętrze, na dużym biurku"},
{q:"Jestem teraz w ... (Kraków)",a:"Krakowie",hint:"-ów → -owie",rule:"Города в Miej.:\n\nKraków → Krakowie\nWrocław → Wrocławiu\nGdańsk → Gdańsku\nWarszawa → Warszawie"},
{q:"Opowiadał o swojej ... (podróż)",a:"podróży",hint:"-ż → -ży",rule:"Жен. на согласную:\n\npodróż → podróży\nnoc → nocy\nmiłość → miłości"},
{q:"Spotkamy się przy ... (fontanna)",a:"fontannie",hint:"-nna → -nnie",rule:"przy + Miej. = у, около:\n\nfontanna → fontannie (nn → nni + e)\n\nprzy fontannie, przy stacji, przy dworcu"},
{q:"Myślę o ... ... (mój syn)",a:"moim synu",hint:"o + муж. Miej.",rule:"Miej. муж.:\n\nПрилаг.: -ój → -oim (mój → moim)\nСущ.: + -u (syn → synu)"},
{q:"Kwiaty na ... (balkon)",a:"balkonie",hint:"муж. + -ie",rule:"Miej. муж. — окончания:\n\n-∅ → -ie (balkon → balkonie)\n-∅ → -u (park → parku)\n\nТвёрдые → -ie с чередованием, мягкие → -u часто"},
{q:"Po ... (obiad) poszliśmy na spacer",a:"obiedzie",hint:"po + Miej., чередование",rule:"po + Miej. = после:\n\nobiad → obiedzie (a → e, d → dzi)\nśniadanie → śniadaniu\nkolacja → kolacji"},
{q:"W ... (ten sklep) jest promocja",a:"tym sklepie",hint:"ten → tym",rule:"Указательные в Miej.:\n\nten → tym (муж./ср.)\nta → tej (жен.)\nci/te → tych (мн.)\n\nw tym sklepie, w tej szkole"},
{q:"Dużo mówi się o ... (zdrowie)",a:"zdrowiu",hint:"ср. -ie → -iu",rule:"Ср. на -ie в Miej.:\n\nzdrowie → zdrowiu\nżycie → życiu\nzdanie → zdaniu\n\no zdrowiu, o życiu, w zdaniu"},
{q:"Byłem na ... (lotnisko)",a:"lotnisku",hint:"ср. -ko → -ku",rule:"Ср. на -ko, -go, -cho в Miej. → -ku:\n\nlotnisko → lotnisku\njabłko → jabłku\nucho → uchu"},
{q:"W ... (ta książka) jest ciekawy rozdział",a:"tej książce",hint:"жен. -ka → -ce",rule:"Жен. на -ka → -ce в Miej.:\n\nksiążka → książce\nręka → ręce\nnoga → nodze (-ga → -dze)\n\nw tej książce, na mojej ręce"}
]},

{id:"cel",icon:"\u{1F3AF}",title:"Дательный (Celownik)",color:"#4361ee",cards:[
{q:"Sara napisała ... (ja) co się wydarzyło",a:"mi",hint:"кому? → mi",rule:"Celownik — кому?\n\nja → mi/mnie\nty → ci/tobie\non → mu/jemu\nona → jej\nmy → nam\nwy → wam\noni → im\n\nmi — короткая, mnie — полная."},
{q:"Ufam moim ... (przyjaciel, мн.ч.)",a:"przyjaciołom",hint:"-om",rule:"Celownik мн.ч.: -om для всех:\n\nprzyjaciel → przyjaciołom\nstudent → studentom\ndziecko → dzieciom"},
{q:"Świat był przeciwko ... (ty)",a:"tobie",hint:"przeciwko + Cel.",rule:"przeciwko + Cel.:\n\nprzeciwko mnie, tobie, niemu\n\nПосле предлогов — полные формы."},
{q:"Film bardzo mi się ... (podobać, on)",a:"podoba",hint:"podobać się + Cel.",rule:"podobać się + Cel. = нравиться кому:\n\nFilm mi się podoba.\nTo ci się nie spodoba.\n\nГлагол согласуется с подлежащим."},
{q:"Kupiłem ... (ona) kwiaty",a:"jej",hint:"кому? → jej",rule:"Cel. 3 лица:\n\non → mu/jemu\nona → jej/niej\noni → im/nim"},
{q:"Pomagam ... (moja siostra)",a:"mojej siostrze",hint:"pomagać + Cel.",rule:"pomagać + Cel.:\n\nmoja → mojej, siostra → siostrze (r→rz)\n\npomagam mojej siostrze, mojemu bratu"},
{q:"Daj ... (my) znać, kiedy przyjedziesz",a:"nam",hint:"dać + Cel.",rule:"dać + Cel.:\n\nmy → nam, wy → wam\n\nТакже + Cel.: powiedzieć, wysłać, obiecać."},
{q:"Gratuluję ... (ty) nowej pracy!",a:"ci",hint:"gratulować + Cel.",rule:"gratulować + Cel. = поздравлять кого:\n\nty → ci (короткая)\n\nGratuluję ci! Gratuluję wam!"},
{q:"Nie przeszkadzaj ... (ja)!",a:"mi",hint:"przeszkadzać + Cel.",rule:"przeszkadzać + Cel. = мешать кому:\n\nNie przeszkadzaj mi!\nHałas mu przeszkadza."},
{q:"Dziecko → ... jest ciemno (Cel.)",a:"dziecku",hint:"ср. род Cel. -u",rule:"Безличные + Cel.:\n\ndziecko → dziecku\n\nDziecku jest zimno.\nMi jest smutno.\nJej jest wstyd."},
{q:"Życzę ... (pan) wszystkiego najlepszego!",a:"panu",hint:"pan → panu в Cel.",rule:"Вежливая форма в Cel.:\n\npan → panu\npani → pani (не меняется!)\n\nŻyczę panu zdrowia!"},
{q:"Opowiedz ... (oni) o wakacjach",a:"im",hint:"oni → im",rule:"Cel. 3 мн.ч.:\n\noni/one → im (короткая) / nim (после предлога)\n\nOpowiedz im. Daj im znać.\nПосле предл.: ku nim, dzięki nim"},
{q:"Dzięki ... (wy) udało się!",a:"wam",hint:"dzięki + Cel.",rule:"dzięki + Cel. = благодаря:\n\ndzięki wam, dzięki tobie, dzięki nam\n\nТакже: dzięki Bogu, dzięki pogodzie"},
{q:"Obiecałem ... (moja mama), że wrócę wcześnie",a:"mojej mamie",hint:"Cel. жен. -a → -ie",rule:"Cel. жен.:\n\nmoja → mojej\nmama → mamie (-a → -ie)\n\nТак же: kobieta → kobiecie, siostra → siostrze"},
{q:"Jest ... (ja) wszystko jedno",a:"mi",hint:"безличное + Cel.",rule:"Безличные выражения + Cel.:\n\nJest mi wszystko jedno. (мне всё равно)\nJest mi zimno. (мне холодно)\nJest mi wstyd. (мне стыдно)\nZależy mi na tym. (мне это важно)"}
]},

{id:"past",icon:"⏪",title:"Прошедшее время",color:"#6a040f",cards:[
{q:"Wczoraj dzieci ... bajki (oglądać)",a:"oglądały",hint:"dzieci → -ły",rule:"Прошедшее — окончания рода:\n\nМуж.: -ł\nЖен.: -ła\nСр.: -ło\nЛич.-муж. мн.: -li\nОст. мн.: -ły\n\ndzieci = нелич.-муж. → -ły"},
{q:"Moi dziadkowie ... się w 1965\n(a) pobrali  (b) ożenili  (c) wyszli za mąż",a:"pobrali",hint:"пара → pobrać się",rule:"pobrać się = пожениться (пара)\nożenić się = жениться (мужчина)\nwyjść za mąż = замуж (женщина)"},
{q:"Na czele urzędu ... Julia Nowak (stanąć)",a:"stanęła",hint:"-ąć → она -ęła",rule:"Глаголы на -ąć:\n\non → stanął\nona → stanęła\noni → stanęli\none → stanęły"},
{q:"Od kiedy ... nowy most (zbudować)",a:"zbudowano",hint:"-no/-to",rule:"Безличная форма (-no/-to):\n\n-ać → -ano: zbudowano\n-ić → -ono: zrobiono\n-ąć → -ęto: wzięto"},
{q:"Mama ... pyszny obiad (ugotować)",a:"ugotowała",hint:"жен. → -ała",rule:"Совершенный вид жен.:\n\nugotować → ugotowała\nnapisać → napisała\nkupić → kupiła"},
{q:"Chłopcy ... do szkoły (biec)",a:"biegli",hint:"лич.-муж. → -li",rule:"biec в прошедшем:\n\non → biegł\nona → biegła\noni → biegli"},
{q:"My ... w parku (siedzieć, смеш. группа)",a:"siedzieliśmy",hint:"my лич.-муж. → -liśmy",rule:"Окончания лица:\n\nja → -łem/-łam\nty → -łeś/-łaś\nmy → -liśmy/-łyśmy"},
{q:"W zeszłym roku ... do Włoch (jechać, ja муж.)",a:"jechałem",hint:"-łem",rule:"ja муж.: -łem (jechałem)\nja жен.: -łam (jechałam)"},
{q:"Ona ... dużo pieniędzy (wydać)",a:"wydała",hint:"wydać → wydała",rule:"wydać (потратить):\n\non → wydał\nona → wydała\noni → wydali\none → wydały"},
{q:"Psy ... po podwórku (biegać)",a:"biegały",hint:"psy = нелич.-муж. → -ły",rule:"Животные = нелично-мужская форма:\n\npsy → biegały (не biegali!)\nkoty → spały\n\nТолько мужчины-люди → -li"},
{q:"Kto ... moje klucze? (wziąć)",a:"wziął",hint:"wziąć → wziął",rule:"wziąć в прошедшем:\n\non → wziął\nona → wzięła\noni → wzięli"},
{q:"Wczoraj ... do 23:00 (pracować, ja жен.)",a:"pracowałam",hint:"ja жен. → -łam",rule:"Ja жен.: -łam: pracowałam\nJa муж.: -łem: pracowałem"},
{q:"... deszcz i ... wiatr (padać, wiać)",a:"padał, wiał",hint:"муж. ед. → -ł",rule:"Погода — 3 лицо ед. муж.:\n\ndeszcz (муж.) → padał\nwiatr (муж.) → wiał"},
{q:"Czy ... (wy, жен.) już na tym filmie?",a:"byłyście",hint:"wy жен. → -łyście",rule:"Vy нелич.-муж. формы:\n\nwy (с мужчинами) → byliście\nwy (без мужчин) → byłyście\n\n-liście / -łyście"},
{q:"Samochód ... (stać) na parkingu przez tydzień",a:"stał",hint:"муж. → -ł",rule:"Неодушевлённые предметы — по грамм. роду:\n\nsamochód (муж.) → stał\nksiążka (жен.) → leżała\nradio (ср.) → grało"},
{q:"Wszystko ... się dobrze (skończyć)",a:"skończyło",hint:"wszystko = ср. → -ło",rule:"wszystko (ср. род) → -ło:\n\nWszystko skończyło się dobrze.\nTo wydarzyło się wczoraj.\nMleko skwaśniało."}
]},

{id:"cond",icon:"\u{1F4AD}",title:"Условное + żeby",color:"#457b9d",cards:[
{q:"Gdybyście mieli kartę, ... tramwajem (jeździć, wy)",a:"jeździlibyście",hint:"прош. + byście",rule:"Условное = прош. + by + лицо:\n\nja → -łbym / -łabym\nty → -łbyś / -łabyś\nmy → -libyśmy\nwy → -libyście"},
{q:"Proszę, żebyś ... ze mną (pójść, ty)",a:"poszedł/poszła",hint:"żebyś + прош.",rule:"żeby + лицо + прош. время:\n\nżebym (ja), żebyś (ty), żeby (on)\nżebyśmy (my), żebyście (wy)"},
{q:"Chciałby, ... (my) częściej spotykali się",a:"żebyśmy",hint:"żeby+śmy",rule:"Окончания к żeby:\n\nżebym, żebyś, żeby\nżebyśmy, żebyście, żeby"},
{q:"Gdybym ... czas, ... nad morze (mieć/pojechać, ja м.)",a:"miał, pojechałbym",hint:"gdybym + прош., -łbym",rule:"Полная конструкция:\n\ngdybym miał czas, pojechałbym\n= если бы было время, поехал бы"},
{q:"Chcielibyśmy ... pizzę (zamówić)",a:"zamówić",hint:"условное + инфинитив",rule:"Условное + инфинитив:\n\nChcielibyśmy zamówić = хотели бы заказать\nChciałbym kupić = хотел бы купить"},
{q:"Wolał, żeby nikt o tym nie ... (wiedzieć)",a:"wiedział",hint:"żeby + 3 ед.",rule:"żeby + 3 лицо (без окончания):\n\nżeby nikt nie wiedział\nżeby nic się nie zmieniło"},
{q:"Na twoim miejscu ... do lekarza (pójść, ja ж.)",a:"poszłabym",hint:"na twoim miejscu = условное",rule:"Na twoim miejscu + условное:\n\nNa twoim miejscu poszłabym do lekarza.\n= На твоём месте я бы пошла к врачу."},
{q:"Gdyby ... (padać) deszcz, ... (zostać, my) w domu",a:"padał, zostalibyśmy",hint:"gdyby + прош., -libyśmy",rule:"Gdyby padał deszcz, zostalibyśmy w domu.\n= Если бы шёл дождь, мы бы остались."},
{q:"Czy mógł... mi pan pomóc? (вежл. просьба)",a:"mógłby",hint:"мог бы = mógłby",rule:"Вежливая просьба с условным:\n\nCzy mógłby mi pan pomóc?\nmógłby (он), mogłaby (она)"},
{q:"Powiedziała, ... (ja м.) zadzwonił wieczorem",a:"żebym",hint:"żeby + m = żebym",rule:"Косвенная речь с żeby:\n\nPowiedziała, żebym zadzwonił.\n= Она сказала, чтобы я позвонил."},
{q:"... pieniądze, kupiłbym nowy laptop (mieć, gdybym)",a:"Gdybym miał",hint:"gdybym + прош.",rule:"Gdybym + прош. время:\n\nGdybym miał pieniądze... = Если бы у меня были деньги...\nGdybym wiedział... = Если бы я знал..."},
{q:"Chciałabym, żeby ... (on) częściej dzwonił",a:"żeby",hint:"3 лицо = żeby без окончания",rule:"3 лицо (on/ona) = просто żeby:\n\nChciałabym, żeby dzwonił.\nProszę, żeby przyszedł.\n\nНет личного окончания в 3 лице!"},
{q:"Byłoby miło, gdybyś ... (przyjść)",a:"przyszedł/przyszła",hint:"gdybyś + прош.",rule:"gdybyś + прош. = если бы ты:\n\ngdybyś przyszedł (м.) / przyszła (ж.)\ngdybyś mógł / mogła\ngdybyś chciał / chciała"},
{q:"Zrobiłbym to, ... (ale, mieć, czas, nie)",a:"ale nie miałbym czasu",hint:"ale nie + условное",rule:"Условное в отрицании:\n\nnie + условное:\nnie miałbym = не имел бы\nnie zrobiłabym = не сделала бы\nnie poszlibyśmy = не пошли бы"}
]},

{id:"ktory",icon:"\u{1F517}",title:"Который (który)",color:"#52796f",cards:[
{q:"Ludzie, ... jedzą zdrowo (który, лич.-муж.)",a:"którzy",hint:"лич.-муж. мн.",rule:"który по родам и числам:\n\nМуж.: który\nЖен.: która\nСр.: które\nЛич.-муж. мн.: którzy\nОст. мн.: które"},
{q:"Osoby, ... tego nie robią (który, жен. мн.)",a:"które",hint:"немуж. мн.",rule:"osoby = жен. мн. → które\n\nДаже о мужчинах — osoby грамм. женский."},
{q:"Mężczyzna, ... tu mieszka (który)",a:"który",hint:"муж. ед. имен.",rule:"który в именительном (подлежащее):\n\nmężczyzna → który\nkobieta → która\ndziecko → które"},
{q:"Film, ... wczoraj oglądałem (который, Biernik)",a:"który",hint:"муж. неодуш. B.=M.",rule:"Biernik муж. неодуш. = Mianownik:\n\nfilm → który (B.=M.)\n\nНо одуш.: mężczyzna, którego spotkałem (B.=Dop.)"},
{q:"Kobieta, z ... rozmawiałem (Narzędnik)",a:"którą",hint:"жен. Narz. = którą",rule:"który в Narzędnik:\n\nЖен.: którą\nМуж.: którym\nМн.: którymi"},
{q:"Sklep, w ... kupuję chleb (Miejscownik)",a:"którym",hint:"муж. Miej. = którym",rule:"który в Miejscownik:\n\nМуж./ср.: którym\nЖен.: której\nМн.: których"},
{q:"Dziecko, ... widziałem w parku (Biernik)",a:"które",hint:"ср. B.=M.",rule:"Ср. род Biernik = Mianownik:\n\ndziecko → które (B.=M.)"},
{q:"Przyjaciel, ... (Celownik) pożyczyłem książkę",a:"któremu",hint:"муж. Cel. = któremu",rule:"który в Celownik:\n\nМуж./ср.: któremu\nЖен.: której\nМн.: którym"},
{q:"Studenci, o ... mówił profesor (Miej. мн.)",a:"których",hint:"мн. Miej. = których",rule:"Мн.ч. Miejscownik:\n\nktórzy/które → których"},
{q:"Dom, obok ... (Dop.) jest park",a:"którego",hint:"муж. Dop. = którego",rule:"który в Dopełniacz:\n\nМуж./ср.: którego\nЖен.: której\nМн.: których"},
{q:"To jest kobieta, ... (Dop.) szukamy",a:"której",hint:"жен. Dop. = której",rule:"Dop. жен. = której:\n\nkobieta, której szukamy\nkobieta, której nie znam\n\nТакже = Miej. жен.: o której mówię"},
{q:"Chłopiec, ... (Biernik одуш.) spotkałem",a:"którego",hint:"одуш. B.=Dop.",rule:"Biernik муж. одуш. = Dopełniacz:\n\nchłopiec → którego (B.=D.)\nfilm → który (B.=M., неодуш.)\n\nОдуш. vs неодуш. — ключевое отличие!"},
{q:"Kraje, do ... (Dop. мн.) chcemy pojechać",a:"których",hint:"мн. Dop. = których",rule:"Мн.ч. Dopełniacz = których:\n\ndo których, bez których, dla których\n\nOдинаково для всех родов во мн.ч."},
{q:"Dziewczyna, ... (Cel.) dałem prezent",a:"której",hint:"жен. Cel. = której",rule:"Celownik жен. = której:\n\ndziewczyna, której dałem prezent\nkobieta, której pomogłem\n\nСовпадает с Dop. жен. (której)!"}
]},

{id:"comp",icon:"⚖️",title:"Степени сравнения",color:"#bc6c25",cards:[
{q:"Amazonka jest ... rzeką niż Wisła (długi)",a:"dłuższą",hint:"długi → dłuższy",rule:"Сравнительная:\n\ndługi → dłuższy\nkrótki → krótszy\ndobry → lepszy\nzły → gorszy\n\nrzeką (жен. Narz.) → dłuższą"},
{q:"Piotr gra ... z całej grupy (dobrze, превосх.)",a:"najlepiej",hint:"→ lepiej → najlepiej",rule:"Наречия:\n\ndobrze → lepiej → najlepiej\nźle → gorzej → najgorzej\ndużo → więcej → najwięcej"},
{q:"Jej koledzy są bardzo ... (miły, лич.-муж.)",a:"mili",hint:"ł → l",rule:"Лич.-муж. мн. — чередования:\n\nmiły → mili (ł→l)\ndobry → dobrzy (r→rz)\nwysoki → wysocy (k→c)"},
{q:"Ten dom jest ... od tamtego (duży)",a:"większy",hint:"неправильная форма",rule:"Неправильные:\n\nduży → większy → największy\nmały → mniejszy → najmniejszy\ndobry → lepszy → najlepszy\nzły → gorszy → najgorszy"},
{q:"Marta biega ... niż Ola (szybko)",a:"szybciej",hint:"-ko → -ciej",rule:"Наречия на -ko:\n\nszybko → szybciej\nwolno → wolniej\ncicho → ciszej"},
{q:"To ... restauracja w mieście (dobry, прев. жен.)",a:"najlepsza",hint:"najlepszy жен. -a",rule:"Превосходная по родам:\n\nМуж.: najlepszy\nЖен.: najlepsza\nСр.: najlepsze"},
{q:"Im ..., tym lepiej (dużo)",a:"więcej",hint:"im + сравн., tym + сравн.",rule:"im... tym... = чем... тем...:\n\nim więcej, tym lepiej\nim starszy, tym mądrzejszy"},
{q:"On jest ... (wysoki) niż jego brat",a:"wyższy",hint:"wysoki → wyższy",rule:"Прилагательные с чередованием:\n\nwysoki → wyższy (k→ż+sz)\nniski → niższy\nszeroki → szerszy"},
{q:"Ta książka jest ... (ciekawy) od tamtej",a:"ciekawsza",hint:"жен. -sza",rule:"Регулярное: ciekawy → ciekawszy / ciekawsza\nładny → ładniejszy / ładniejsza"},
{q:"To ... (mały) mieszkanie w tym budynku",a:"najmniejsze",hint:"ср. род превосх.",rule:"Превосходная ср. рода:\n\nmały → mniejszy → najmniejszy\nСр.: najmniejsze"},
{q:"Dziś jest ... (zimno) niż wczoraj",a:"zimniej",hint:"-no → -niej",rule:"Наречия на -no:\n\nzimno → zimniej\nciepło → cieplej\nciemno → ciemniej\njasno → jaśniej"},
{q:"To jest ... (stary) kościół w Polsce",a:"najstarszy",hint:"превосх. муж.",rule:"stary → starszy → najstarszy\n\nnajstarszy kościół = самый старый костёл\n\nТак же: młody → młodszy → najmłodszy"},
{q:"Ten egzamin był ... (trudny) niż poprzedni",a:"trudniejszy",hint:"-ny → -niejszy",rule:"Регулярное -ny → -niejszy:\n\ntrudny → trudniejszy\nładny → ładniejszy\nsmaczny → smaczniejszy\nważny → ważniejszy"},
{q:"Mówi po polsku coraz ... (dobrze)",a:"lepiej",hint:"coraz + сравн.",rule:"coraz + сравнительная = всё более:\n\ncoraz lepiej = всё лучше\ncoraz szybciej = всё быстрее\ncoraz trudniej = всё труднее"}
]},

{id:"num",icon:"\u{1F522}",title:"Числительные",color:"#6d6875",cards:[
{q:"74 − 23 = ? (словами)",a:"pięćdziesiąt jeden",hint:"50+1",rule:"Десятки:\n50 pięćdziesiąt, 60 sześćdziesiąt,\n70 siedemdziesiąt, 80 osiemdziesiąt\n\n74 − 23 = 51 = pięćdziesiąt jeden"},
{q:"1956 год (w ... roku)",a:"tysiąc dziewięćset pięćdziesiątym szóstym",hint:"Miej. порядкового",rule:"Годы: w + Miej. порядкового:\n\nСклоняется только последняя часть:\n1956 = tysiąc dziewięćset pięćdziesiątym szóstym"},
{q:"Mają ... dzieci (3, собират.)",a:"troje",hint:"дети → собирательное",rule:"Собирательные:\n2 = dwoje, 3 = troje, 4 = czworo, 5 = pięcioro\n\ntroje dzieci (не *trzy dzieci!)"},
{q:"Film od ... (12 lat)",a:"dwunastu lat",hint:"od + Dop.",rule:"Числительные 11-19 в Dop.:\n\n11 = jedenastu\n12 = dwunastu\n13 = trzynastu"},
{q:"Zamówiłem ... (2) piwa",a:"dwa",hint:"ср. род → dwa",rule:"Числительные по родам (2):\n\nМуж. лич.: dwóch/dwaj\nМуж. нелич./ср.: dwa\nЖен.: dwie"},
{q:"W pokoju jest ... (5) krzeseł",a:"pięć",hint:"5+ → pięć + Dop. мн.",rule:"5+ → + Dop. мн.:\n\npięć krzeseł, sześć osób, dziesięć minut\n\n2-4 + Mian. мн.: dwa krzesła"},
{q:"Za ... minut (15) będziemy na miejscu",a:"piętnaście",hint:"za + Biernik",rule:"za + Biernik = через:\n\nza piętnaście minut\nza godzinę\nza dwa dni"},
{q:"Mam ... (4) koty",a:"cztery",hint:"2-4 + Mian. мн.",rule:"Числительные 2-4 + Mianownik мн.:\n\ndwa koty, trzy koty, cztery koty\n\nНо 5+: pięć kotów (Dop. мн.)"},
{q:"Potrzebuję ... (100) złotych",a:"stu",hint:"100 в Dop. = stu",rule:"sto (100) по падежам:\n\nMian.: sto\nDop.: stu\nBiernik: sto\nNarz.: stu\nMiej.: stu"},
{q:"Przyjdę za ... (1) godzinę",a:"jedną",hint:"жен. Biernik = jedną",rule:"jeden по родам в Biernik:\n\nМуж. одуш.: jednego\nЖен.: jedną\nСр.: jedno"},
{q:"Zapłaciłem ... (200) złotych",a:"dwieście",hint:"200 = dwieście",rule:"Сотни:\n100 = sto, 200 = dwieście\n300 = trzysta, 400 = czterysta\n500 = pięćset"},
{q:"Na koncercie było ... (1000) osób",a:"tysiąc",hint:"tysiąc + Dop. мн.",rule:"tysiąc = 1000\n\ntysiąc + Dop. мн.:\ntysiąc osób, tysiąc złotych\n\ndwa tysiące (2000), pięć tysięcy (5000)"},
{q:"Mam ... (22) lata",a:"dwadzieścia dwa",hint:"22 + Mian. мн.",rule:"Возраст — числительные:\n\n1 rok, 2/3/4 lata, 5+ lat\n\n22 lata (2-4 на конце → lata)\n25 lat (5+ на конце → lat)"},
{q:"To kosztuje ... (31) złotych",a:"trzydzieści jeden",hint:"31 zlotych",rule:"Валюта — числительные:\n\n1 złoty, 2/3/4 złote, 5+ złotych\n\n31 złotych (1 на конце, но > 20 → złotych)"},
{q:"Na parkingu stoi ... (3) autobusy",a:"trzy",hint:"2-4 + Mian. мн.",rule:"2-4 + Mianownik мн.:\n\ntrzy autobusy, dwa samochody\n\nНо: pięć autobusów (5+ → Dop. мн.)"}
]},

{id:"idiom",icon:"\u{1F4AC}",title:"Идиомы и лексика",color:"#5a189a",cards:[
{q:"Kasia ma świetne pomysły — ma ...\n(a) głowę na karku  (b) pstro w głowie",a:"głowę na karku",hint:"смекалистая",rule:"głowę na karku = смекалистый, с головой.\npstro w głowie = легкомысленный."},
{q:"Zarabia mało. Pracuje ...\n(a) za pół darmo  (b) na czarno  (c) jak szalony",a:"za pół darmo",hint:"за копейки",rule:"za pół darmo = за копейки.\nna czarno = нелегально.\njak szalony = очень много."},
{q:"Ma 15 kg ...\n(a) nadwagi  (b) wagi  (c) przewagi",a:"nadwagi",hint:"лишний вес",rule:"nadwaga = лишний вес\nwaga = вес (нейтрально)\nprzewaga = преимущество"},
{q:"Wysyłam serdeczne ... z wakacji\n(a) witania  (b) pozdrowienia  (c) życzenia",a:"pozdrowienia",hint:"приветы с отдыха",rule:"pozdrowienia = приветы\nżyczenia = пожелания (праздник)"},
{q:"Niczego się nie ...\n(a) przerobił  (b) dorobił  (c) zrobił",a:"dorobił",hint:"нажить",rule:"dorobić się = нажить\nprzerobić = переделать\nzrobić = сделать"},
{q:"Lena ma ... zdać egzamin (nadzieja)",a:"nadzieję",hint:"mieć nadzieję",rule:"mieć nadzieję = надеяться\n\nnadzieja → nadzieję (Biernik: -a → -ę)"},
{q:"Nie mam ... na spacer (ochota)",a:"ochoty",hint:"nie mieć + Dop.",rule:"Отрицание + Dop.:\n\nMam ochotę (утв., Biernik)\nNie mam ochoty (отр., Dop.)"},
{q:"Nie ma ... (pojęcie), co robić",a:"pojęcia",hint:"nie mieć pojęcia",rule:"nie mieć pojęcia = не иметь понятия\n\npojęcie → pojęcia (Dop.)"},
{q:"Wzięli sprawy w swoje ...\n(a) ręce  (b) ręki  (c) rękę",a:"ręce",hint:"в свои руки",rule:"wziąć w swoje ręce = взять в руки\n\nręce = мн.ч. Biernik (=Mian.)"},
{q:"On zawsze ... z siebie\n(a) robi  (b) robi się  (c) robi sobie",a:"robi",hint:"строить из себя",rule:"robić z siebie (głupka/bohatera) = строить из себя"},
{q:"To mi ... w grę!\n(a) nie wchodzi  (b) nie wejdzie  (c) nie wchodzą",a:"nie wchodzi",hint:"не обсуждается",rule:"nie wchodzić w grę = не обсуждается\n\nTo nie wchodzi w grę!"},
{q:"Mam tego ...!\n(a) dosyć  (b) dość  (c) оба верны",a:"оба верны",hint:"dosyć = dość",rule:"dosyć / dość = довольно, хватит\n\nMam tego dosyć! = Mam tego dość!"},
{q:"Nie warto robić z ... widły\n(a) igły  (b) igłą  (c) igłę",a:"igły",hint:"z + Dop.",rule:"robić z igły widły = делать из мухи слона\n\nz + Dop.: igła → igły"},
{q:"Życzę ... ... (ty, powodzenie)!",a:"ci powodzenia",hint:"życzyć + Cel. + Dop.",rule:"życzyć + Cel. (кому) + Dop. (чего):\n\nty → ci, powodzenie → powodzenia"},
{q:"Nie mogę się ... (zdecydować)\n(a) zdecydować  (b) decydować  (c) оба",a:"zdecydować",hint:"nie móc + сов. вид",rule:"nie móc + инфинитив (чаще соверш.):\n\nNie mogę się zdecydować.\n= Не могу решиться.\n\nzdecydować = сов., decydować = несов."},
{q:"Muszę to ... do jutra (zrobić / robić)",a:"zrobić",hint:"musieć + сов. вид",rule:"musieć + инфинитив (чаще соверш.):\n\nMuszę to zrobić = Должен сделать (результат)\nMuszę to robić = Должен делать (процесс)\n\nДо дедлайна → совершенный вид"},
{q:"Daj ... (spokój)! Zostaw mnie!\n(a) spokój  (b) spokoju  (c) spokojem",a:"spokój",hint:"daj + Biernik",rule:"dać + Biernik:\n\nDaj spokój! = Оставь в покое! / Да ладно!\n\nspokój (муж. неодуш.) B. = M. = spokój"}
]},

{id:"po",icon:"⏭️",title:"po + причастия / предлоги",color:"#3a5a40",cards:[
{q:"Zaczniemy wakacje po ... egzaminów (zdać)",a:"zdaniu",hint:"po + Miej.",rule:"po + отглагольное сущ. в Miej.:\n\nzdać → zdanie → po zdaniu\nskończyć → skończenie → po skończeniu"},
{q:"Przyszedł spóźniony, ale ... (uczesać się)",a:"uczesany",hint:"причастие",rule:"Причастие = состояние:\n\nuczesać → uczesany\nspóźnić się → spóźniony\nzmęczyć się → zmęczony"},
{q:"Ona mówi, że to przez ... (on)",a:"niego",hint:"через + Biernik",rule:"przez + B. (виновник), предлог → n-:\n\non → niego (не go!)\nona → nią (не ją!)"},
{q:"Jestem ... po pracy (zmęczyć się)",a:"zmęczony/zmęczona",hint:"быть + причастие",rule:"być + причастие:\n\nzmęczony/zmęczona\nzajęty/zajęta\nzdenerwowany/a"},
{q:"Po ... filmu poszliśmy do domu (obejrzeć)",a:"obejrzeniu",hint:"po + Miej.",rule:"po + отглагольное:\n\nobejrzeć → obejrzenie → po obejrzeniu\nzjeść → zjedzenie → po zjedzeniu"},
{q:"Drzwi są ... (zamknąć)",a:"zamknięte",hint:"мн. причастие -ęte",rule:"Причастия от -ąć:\n\nzamknąć → zamknięty/a/e\nwziąć → wzięty/a/e"},
{q:"List jest ... po polsku (napisać)",a:"napisany",hint:"-ać → -any",rule:"Причастия от -ać → -any:\n\nnapisać → napisany\nprzeczytać → przeczytany\nzrobić → zrobiony (-ić → -ony)"},
{q:"Obiad już ... (ugotować, причастие)",a:"ugotowany",hint:"-ować → -owany",rule:"Причастия от -ować → -owany:\n\nugotować → ugotowany\nzorganizować → zorganizowany"},
{q:"Po ... (przyjść) do domu od razu poszedł spać",a:"przyjściu",hint:"po + przyjście → przyjściu",rule:"Отглагольные от идти:\n\nprzyjść → przyjście → po przyjściu\nwyjść → wyjście → po wyjściu"},
{q:"Jestem ... (zainteresować) tą ofertą",a:"zainteresowany/zainteresowana",hint:"-ować → -owany",rule:"Причастие-прилагательное:\n\nzainteresowany = заинтересованный\nzaskoczony = удивлённый\nzmęczony = уставший"},
{q:"Samochód jest ... (naprawić)",a:"naprawiony",hint:"-ić → -ony",rule:"Причастия от -ić → -ony:\n\nnaprawić → naprawiony\nkupić → kupiony\nzrobić → zrobiony\n\nSamochód jest naprawiony."},
{q:"Sklep jest ... (otworzyć) od 9:00",a:"otwarty",hint:"неправильное причастие",rule:"Неправильные причастия:\n\notworzyć → otwarty (не *otworzony!)\nzakryć → zakryty\nodkryć → odkryty\n\nSklep jest otwarty od 9:00."},
{q:"Po ... (wstać) zrobiłam kawę",a:"wstaniu",hint:"po + wstanie → wstaniu",rule:"po + Miej. от отглагольного:\n\nwstać → wstanie → po wstaniu\nzjeść → zjedzenie → po zjedzeniu\nwypiciu kawy = после кофе"},
{q:"Jestem ... (rozczarować) wynikiem",a:"rozczarowany/rozczarowana",hint:"-ować → -owany + Narz.",rule:"Причастие + Narzędnik (чем?):\n\nrozczarowany wynikiem = разочарован результатом\nzadowolony pracą = доволен работой\nzachwycony filmem = восхищён фильмом"}
]}
];

// Лекции из учебника — отдельная секция
var L=[
{id:"lek5",icon:"📖",title:"Lekcja 5 — Co lubisz robić?",color:"#00838f",cards:[
// --- Словарь: хобби ---
{q:"Как сказать «бегать» по-польски?",a:"biegać",hint:"спорт",rule:"Хобби — спорт:\n\nbiegać = бегать\npływać = плавать\nuprawiać sport = заниматься спортом\njeździć na rowerze = кататься на велосипеде\njeździć na nartach = кататься на лыжах"},
{q:"Как сказать «кататься на велосипеде»?",a:"jeździć na rowerze",hint:"jeździć na + Miej.",rule:"jeździć na + Miejscownik:\n\nna rowerze (велосипед)\nna nartach (лыжи)\nna snowboardzie"},
{q:"Lubię ... po górach (ходить)",a:"chodzić",hint:"chodzić po + Miej.",rule:"chodzić po + Miejscownik = ходить по:\n\nchodzić po górach = ходить по горам\nchodzić po mieście = ходить по городу"},
{q:"Lubię ... na gitarze (играть)",a:"grać",hint:"grać na + инструмент",rule:"Играть на инструменте: grać na + Miejscownik:\n\ngrać na gitarze, grać na saksofonie, grać na pianinie\n\nИграть в (спорт): grać w + Biernik:\ngrać w tenisa, grać w karty, grać w piłkę nożną"},
{q:"Lubię ... zdjęcia (делать)",a:"robić",hint:"robić zdjęcia",rule:"robić zdjęcia = делать фотографии\nrobić zakupy = делать покупки\n\nrobić — II спр.: robię, robisz, robi, robimy, robicie, robią"},
{q:"Lubię ... się z kolegami (встречаться)",a:"spotykać",hint:"spotykać się z + Narz.",rule:"spotykać się z + Narzędnik = встречаться с:\n\nz kolegami, z przyjaciółmi, z rodzicami\n\nspotykam się, spotykasz się, spotyka się..."},
{q:"Lubię ... telewizję (смотреть)",a:"oglądać",hint:"-ać, I спр.",rule:"oglądać telewizję = смотреть телевизор\n\noglądać — I спр.:\noglądam, oglądasz, ogląda\noglądamy, oglądacie, oglądają"},
{q:"Lubię ... muzyki (слушать)",a:"słuchać",hint:"słuchać + Dop.!",rule:"słuchać + Dopełniacz = слушать чего:\n\nsłuchać muzyki (не *muzykę!)\nsłuchać radia\nsłuchać wykładu\n\nВнимание: Biernik ожидается, но słuchać требует Dop.!"},
// --- Структуры: lubić + bezok. / lubić + Biernik / interesować się + Narz. ---
{q:"Anna lubi czytać książki.\nЧто стоит после lubić?",a:"bezokolicznik",hint:"инфинитив",rule:"Три способа говорить о хобби:\n\n1. lubić + bezokolicznik: Lubię czytać książki.\n2. lubić + Biernik: Lubię literaturę.\n3. interesować się + Narzędnik: Interesuję się literaturą.\n\nВсе три = одно значение, разные конструкции."},
{q:"Lubię chodzić do kina.\n= Lubię ... (сущ. в Biernik)",a:"kino",hint:"lubić + Biernik",rule:"lubić + Biernik (сущ.):\n\nLubię kino. = Lubię chodzić do kina.\nLubię sport. = Lubię uprawiać sport.\nLubię muzykę. = Lubię słuchać muzyki."},
{q:"Lubię kino.\n= Interesuję się ... (Narzędnik)",a:"kinem",hint:"kino → kinem",rule:"interesować się + Narzędnik:\n\nkino → kinem\nliteratura → literaturą\nmuzyka → muzyką\nsport → sportem\n\nInteresuję się kinem. = Интересуюсь кино."},
{q:"Dorota i Renata lubią chodzić do kina.\n= One lubią ... = Interesują się ...",a:"kino / kinem",hint:"Biernik / Narzędnik",rule:"Три формы одной мысли:\n\n1. lubią chodzić do kina (инфинитив)\n2. lubią kino (Biernik)\n3. interesują się kinem (Narzędnik)"},
{q:"Mój brat lubi czytać książki.\n= On lubi ... = Interesuje się ...",a:"literaturę / literaturą",hint:"Biernik / Narzędnik",rule:"lubić + Biernik: lubi literaturę\ninteresować się + Narz.: interesuje się literaturą\n\nliteratura → literaturę (B.) / literaturą (N.)"},
{q:"Nasz kuzyn lubi śpiewać i grać na gitarze.\n= On lubi ... = Interesuje się ...",a:"muzykę / muzyką",hint:"Biernik / Narzędnik",rule:"muzyka → muzykę (Biernik) / muzyką (Narzędnik)\n\nLubi muzykę. = Interesuje się muzyką."},
{q:"Lubimy podróżować po Polsce.\n= Lubimy ... = Interesujemy się ...",a:"geografię / geografią",hint:"Biernik / Narzędnik",rule:"geografia → geografię (B.) / geografią (N.)\n\nLubimy geografię.\nInteresujemy się geografią."},
// --- Выбор слов ---
{q:"Bardzo lubię grać w ... – na przykład w brydża.\n(a) karty  (b) sport  (c) piłkę",a:"karty",hint:"grać w karty",rule:"grać w + Biernik (игра):\n\ngrać w karty = играть в карты\ngrać w brydża = играть в бридж\ngrać w tenisa, w piłkę nożną, w szachy"},
{q:"On nie lubi ... do teatru.\n(a) iść  (b) chodzić  (c) biegać",a:"chodzić",hint:"lubić + chodzić (привычка)",rule:"lubić + инфинитив (привычное действие):\n\nlubić chodzić do teatru (ходить в театр)\nlubić chodzić do kina\nlubić chodzić na koncerty"},
{q:"Czy ... chodzić do teatru? (ты)\n(a) lubię  (b) lubisz  (c) lubi",a:"lubisz",hint:"ty → lubisz",rule:"lubić — II спр. (-ę, -isz):\n\nja → lubię\nty → lubisz\non → lubi\nmy → lubimy\nwy → lubicie\noni → lubią"},
{q:"On bardzo lubi ... w Parku Wodnym.\n(a) pływać  (b) biegać  (c) jeździć",a:"pływać",hint:"Park Wodny = бассейн",rule:"pływać = плавать\n\nPark Wodny = аквапарк/бассейн"},
{q:"Bardzo lubimy ... po Europie.\n(a) jeździć  (b) podróżować  (c) chodzić",a:"podróżować",hint:"путешествовать",rule:"podróżować = путешествовать\n\npodróżować po + Miejscownik:\npo Europie, po Polsce, po świecie"},
{q:"Moja przyjaciółka lubi ... na dyskotece.\n(a) śpiewać  (b) tańczyć  (c) grać",a:"tańczyć",hint:"на дискотеке танцуют",rule:"tańczyć = танцевать\n\ntańczyć na dyskotece = танцевать на дискотеке\n\ntańczyć — II спр.: tańczę, tańczysz, tańczy..."},
{q:"One lubią słuchać ... rockowej.\n(a) muzyka  (b) muzykę  (c) muzyki",a:"muzyki",hint:"słuchać + Dop.",rule:"słuchać + Dopełniacz:\n\nmuzyka → muzyki (Dop.)\n\nsłuchać muzyki rockowej\nsłuchać muzyki klasycznej"},
// --- Jak często? ---
{q:"Расставь по убыванию частоты:\nrzadko, zawsze, często, nigdy nie, codziennie",a:"zawsze, codziennie, często, rzadko, nigdy nie",hint:"от 100% к 0%",rule:"Наречия частотности (jak często?):\n\nzawsze = всегда (100%)\ncodziennie = каждый день\nzwykle = обычно\nczęsto = часто\nod czasu do czasu = время от времени\nrzadko = редко\nnigdy nie = никогда (0%)"},
{q:"Pan Kowalski ... wieczorem czyta książki (100%)",a:"zawsze",hint:"= всегда",rule:"zawsze = всегда\n\nZawsze wieczorem czyta książki."},
{q:"... gra na gitarze klasycznej (каждый день)",a:"Codziennie",hint:"co + dzień",rule:"codziennie = каждый день\n\nCodziennie gra na gitarze."},
{q:"... chodzi do teatru, bo nie ma czasu (редко)",a:"Rzadko",hint:"мало",rule:"rzadko = редко\n\nRzadko chodzi do teatru.\nbo nie ma czasu = потому что нет времени"},
{q:"... nie słucha muzyki dyskotekowej (никогда)",a:"Nigdy",hint:"0% + nie",rule:"nigdy nie = никогда не\n\nNigdy nie słucha muzyki dyskotekowej.\n\nДвойное отрицание обязательно!\nnigdy nie = никогда не"},
{q:"Антоним: Nigdy nie chodzimy do kina. ≠ ...",a:"Zawsze chodzimy do kina.",hint:"никогда ≠ всегда",rule:"Пары антонимов:\n\nnigdy nie ≠ zawsze\nrzadko ≠ często\nczęsto ≠ rzadko"},
// --- Koniugacje ---
{q:"mieszkać → (ja) ..., (oni) ...",a:"mieszkam, mieszkają",hint:"-m, -sz",rule:"Koniugacja -m, -sz:\n\nmieszkać:\nmieszkam, mieszkasz, mieszka\nmieszkamy, mieszkacie, mieszkają\n\nТак же: czytać, słuchać, grać, biegać"},
{q:"jeść → (ja) ..., (oni) ...",a:"jem, jedzą",hint:"неправильный, -m/-sz",rule:"jeść — неправильный (-m, -sz):\n\njem, jesz, je\njemy, jecie, jedzą"},
{q:"mówić → (ja) ..., (oni) ...",a:"mówię, mówią",hint:"-ę, -isz",rule:"Koniugacja -ę, -isz:\n\nmówić: mówię, mówisz, mówi\nmówimy, mówicie, mówią\n\nТак же: lubić, robić, chodzić"},
{q:"tańczyć → (ja) ..., (my) ...",a:"tańczę, tańczymy",hint:"-ę, -ysz",rule:"Подтип -ę, -ysz:\n\ntańczyć: tańczę, tańczysz, tańczy\ntańczymy, tańczycie, tańczą"},
{q:"pisać → (ja) ..., (ty) ...",a:"piszę, piszesz",hint:"-ę, -esz",rule:"Koniugacja -ę, -esz:\n\npisać: piszę, piszesz, pisze\npiszemy, piszecie, piszą\n\nЧередование s → sz"},
{q:"chcieć → (ja) ..., (on) ..., (oni) ...",a:"chcę, chce, chcą",hint:"-ę, -esz неправ.",rule:"chcieć — неправильный:\n\nchcę, chcesz, chce\nchcemy, chcecie, chcą"},
{q:"studiować → (ja) ..., (on) ..., (oni) ...",a:"studiuję, studiuje, studiują",hint:"-ować → -uję",rule:"Koniugacja -ować → -uj-:\n\nstudiować: studiuję, studiujesz, studiuje\nstudiujemy, studiujecie, studiują\n\nТак же: pracować, mailować, surfować"},
{q:"pracować → (my) ..., (wy) ...",a:"pracujemy, pracujecie",hint:"-ować → -ujemy",rule:"pracować:\npracuję, pracujesz, pracuje\npracujemy, pracujecie, pracują"},
// --- Ćw. 7: спряжение в контексте ---
{q:"Dwa samoloty ... (lądować, oni)",a:"lądują",hint:"-ować, oni",rule:"lądować → lądują (oni)\n\n-ować → -uj- + окончания"},
{q:"Marek ... samochód (parkować, on)",a:"parkuje",hint:"-ować, on",rule:"parkować → parkuje (on)"},
{q:"(ja) ... historią (interesować się)",a:"interesuję się",hint:"-ować, ja",rule:"interesować się → interesuję się\n\ninteresować się + Narzędnik"},
{q:"One pięknie ... (śpiewać)",a:"śpiewają",hint:"one → -ają",rule:"śpiewać — I спр.:\nśpiewam, śpiewasz, śpiewa\nśpiewamy, śpiewacie, śpiewają"},
{q:"(ja) ... słabo po polsku (mówić)",a:"mówię",hint:"-ę, -isz, ja",rule:"mówić: mówię, mówisz, mówi\n\nmówić po polsku = говорить по-польски"},
{q:"Co oni ... codziennie? (robić)",a:"robią",hint:"oni → -ią",rule:"robić: robię, robisz, robi\nrobimy, robicie, robią"},
{q:"Co (ty) ... robić dzisiaj wieczorem? (chcieć)",a:"chcesz",hint:"-ę, -esz, ty",rule:"chcieć: chcę, chcesz, chce\nchcemy, chcecie, chcą"},
{q:"Czy (wy) ... powtórzyć numer? (móc)",a:"możecie",hint:"wy → -ecie",rule:"móc: mogę, możesz, może\nmożemy, możecie, mogą"},
// --- Biernik / Narzędnik ---
{q:"On interesuje się ... (francuski sport)",a:"francuskim sportem",hint:"interesować się + Narz.",rule:"Narzędnik:\n\nfrancuski → francuskim\nsport → sportem\n\ninteresuje się francuskim sportem"},
{q:"Bardzo lubię ... (niemiecka kuchnia)",a:"niemiecką kuchnię",hint:"lubić + Biernik",rule:"Biernik жен.:\n\nniemiecka → niemiecką\nkuchnia → kuchnię\n\nlubię niemiecką kuchnię"},
{q:"Lubisz ... ? (muzyka klasyczna, Biernik)",a:"muzykę klasyczną",hint:"lubić + Biernik жен.",rule:"Biernik жен.:\n\nmuzyka → muzykę\nklasyczna → klasyczną\n\n-a → -ę (сущ.), -a → -ą (прилаг.)"},
{q:"Interesujesz się ...? (muzyka hiszpańska)",a:"muzyką hiszpańską",hint:"int. się + Narz.",rule:"Narzędnik жен.:\n\nmuzyka → muzyką\nhiszpańska → hiszpańską\n\n-a → -ą (и сущ., и прилаг.)"},
{q:"Oni interesują się ... (literatura angielska)",a:"literaturą angielską",hint:"int. się + Narz.",rule:"Narzędnik жен.:\n\nliteratura → literaturą\nangielska → angielską"},
{q:"Interesujesz się ...? (filozofia)",a:"filozofią",hint:"-ia → -ią",rule:"Narzędnik жен. на -ia:\n\nfilozofia → filozofią\nhistoria → historią\ngeografia → geografią"},
// --- Предлоги ---
{q:"Lubimy podróżować ... Europie.\n(a) po  (b) w  (c) na",a:"po",hint:"podróżować po + Miej.",rule:"podróżować po + Miejscownik:\n\npo Europie, po Polsce, po świecie"},
{q:"Grażyna świetnie gra ... saksofonie.\n(a) w  (b) na  (c) do",a:"na",hint:"grać na + инструмент",rule:"grać na + Miejscownik (инструмент):\n\nna saksofonie, na gitarze, na pianinie\n\nНо: grać w + Biernik (игра): w tenisa, w karty"},
{q:"Czy lubisz chodzić ... dyskotekę?\n(a) do  (b) na  (c) w",a:"na",hint:"на мероприятие = na",rule:"chodzić na + Biernik (мероприятие):\n\nna dyskotekę, na koncert, na basen\n\nНо: chodzić do + Dop. (здание):\ndo teatru, do kina, do restauracji"},
{q:"Często chodzimy ... restauracji.\n(a) na  (b) do  (c) w",a:"do",hint:"do + Dop. (здание)",rule:"chodzić do + Dopełniacz:\n\ndo restauracji, do kina, do teatru\ndo kawiarni, do muzeum"},
{q:"Nie umiem grać ... karty.\n(a) na  (b) w  (c) z",a:"w",hint:"grać w + игра",rule:"grać w + Biernik (игра):\n\nw karty, w tenisa, w piłkę nożną, w szachy\n\ngrać na + Miej. (инструмент):\nna gitarze, na pianinie"}
]}
];
