// Polski Trener — данные карточек
// Редактируйте вопросы здесь. Формат:
//   q: вопрос, a: ответ (через / для альтернатив), hint: подсказка, rule: правило
var T=[
{id:"conj",icon:"\u{1F504}",title:"Спряжение глаголов",color:"#2d6a4f",cards:[
{q:"pracować → Ola i Daniel ... (oni)",a:"pracują",hint:"-ują (I спр.)",rule:"I спряжение: -ować → -uj-\n\nja → pracuję\nty → pracujesz\non → pracuje\nmy → pracujemy\nwy → pracujecie\noni → pracują\n\nТак же: kupować → kupuję, budować → buduję"},
{q:"chodzić → Często ... po górach (ja)",a:"chodzę",hint:"-ę (II спр.)",rule:"II спряжение (-ę, -isz): глаголы на -ić.\n\nja → chodzę\nty → chodzisz\non → chodzi\nmy → chodzimy\nwy → chodzicie\noni → chodzą\n\nЧередование dz/dzi в 1 ед. и 3 мн."},
{q:"zamawiać → Oni ... jedzenie",a:"zamawiają",hint:"-ają",rule:"I спр.: глаголы на -ać, основа -aj-\n\nja → zamawiam\nty → zamawiasz\non → zamawia\noni → zamawiają\n\nТак же: wysyłać → wysyłają, czekać → czekają"},
{q:"wiedzieć → Oni nie ... jak dojść",a:"wiedzą",hint:"неправильный",rule:"wiedzieć — неправильный:\n\nja → wiem\nty → wiesz\non → wie\nmy → wiemy\noni → wiedzą\n\n3 мн.ч. = wiedzą (не wiezą!)"},
{q:"mieć → 80% Polaków ... zwierzę",a:"ma",hint:"% + ед.ч. глагола",rule:"Процент/большинство → глагол в 3 ед.ч.:\n\n80% Polaków ma... (не mają!)\nWiększość studentów uczy się...\nPołowa ludzi nie wie..."},
{q:"pisać → Co ty ...? (ty)",a:"piszesz",hint:"s→sz, I спр.",rule:"pisać — I спр. с чередованием s→sz:\n\nja → piszę\nty → piszesz\non → pisze\noni → piszą\n\nТак же: kazać → każę, tańczyć → tańczę"},
{q:"jeść → Dzieci ... obiad o 13:00",a:"jedzą",hint:"неправильный",rule:"jeść — неправильный:\n\nja → jem\nty → jesz\non → je\nmy → jemy\noni → jedzą"},
{q:"robić → Co ... w weekend? (wy)",a:"robicie",hint:"-icie (II спр.)",rule:"robić — II спр.:\n\nja → robię\nty → robisz\non → robi\nwy → robicie\noni → robią"},
{q:"umieć → Ona ... dobrze gotować",a:"umie",hint:"-eć → -ie",rule:"umieć — II спр.:\n\nja → umiem\nty → umiesz\non → umie\noni → umieją\n\nТак же: rozumieć → rozumiem"},
{q:"musieć → ... iść do lekarza (ja)",a:"muszę",hint:"s→sz",rule:"musieć — II спр. с чередованием:\n\nja → muszę\nty → musisz\non → musi\noni → muszą\n\nЧередование s→sz в 1 ед. и 3 мн."},
{q:"móc → Czy ... mi pomóc? (ty)",a:"możesz",hint:"I спр., неправильный",rule:"móc — неправильный:\n\nja → mogę\nty → możesz\non → może\nmy → możemy\noni → mogą\n\nЧередование g→ż: mogę/możesz"},
{q:"lubić → Bardzo ... czekoladę (ja)",a:"lubię",hint:"II спр. -ię",rule:"lubić — II спр.:\n\nja → lubię\nty → lubisz\non → lubi\noni → lubią\n\nТак же: robić, mówić, prosić"},
{q:"spać → Kot ... na kanapie (on)",a:"śpi",hint:"неправильный, II спр.",rule:"spać — неправильный, II спр.:\n\nja → śpię\nty → śpisz\non → śpi\nmy → śpimy\noni → śpią\n\nЧередование sp→śp"},
{q:"brać → Ile ... za lekcję? (ty)",a:"bierzesz",hint:"I спр., чередование",rule:"brać — I спр. с чередованием:\n\nja → biorę\nty → bierzesz\non → bierze\nmy → bierzemy\noni → biorą\n\nВнимание: biorę/biorą (1,3), bierzesz (ост.)"},
{q:"myć → Mama ... naczynia (ona)",a:"myje",hint:"I спр., -yć → -yje",rule:"myć — I спр.:\n\nja → myję\nty → myjesz\non → myje\noni → myją\n\nТак же: żyć → żyję, szyć → szyję"},
{q:"czytać → Ania ... książkę (ona)",a:"czyta",hint:"I спр. -ać → -a",rule:"I спр. -ać → -a- :\n\nja → czytam\nty → czytasz\non → czyta\nmy → czytamy\noni → czytają\n\nТак же: słuchać, kochać, grać, pytać"},
{q:"uczyć się → My ... polskiego (my)",a:"uczymy się",hint:"II спр. + się",rule:"uczyć się — II спр.:\n\nja → uczę się\nty → uczysz się\non → uczy się\nmy → uczymy się\noni → uczą się\n\nЧередование cz/cz в основе"},
{q:"woleć → ... herbatę niż kawę (ja)",a:"wolę",hint:"II спр. -eć → -ę",rule:"woleć — II спр.:\n\nja → wolę\nty → wolisz\non → woli\nmy → wolimy\noni → wolą\n\nwoleć = предпочитать\nWolę X niż Y."}
]},

{id:"znac",icon:"\u{1F9E0}",title:"znać vs wiedzieć",color:"#7b2cbf",cards:[
{q:"Julia ... język hiszpański.\n(a) zna  (b) wie",a:"zna",hint:"znać + сущ.",rule:"znać = знать кого/что (+ существительное):\n• Znam język polski.\n• Znasz tę osobę?\n\nwiedzieć = знать (+ придаточное: że, jak, co):\n• Wiem, że to prawda.\n\nТест: «кого/что?» → znać. «Что? как?» → wiedzieć."},
{q:"Oni nie ..., jak dojść do parku.\n(a) znają  (b) wiedzą",a:"wiedzą",hint:"wiedzieć + jak",rule:"wiedzieć + придаточное (jak, że, co, gdzie).\n\nNie wiedzą, jak dojść...\nWiem, że masz rację.\n\nznać — только с дополнением: Znam tę drogę."},
{q:"... pan tę restaurację?\n(a) Zna  (b) Wie",a:"Zna",hint:"знать что → znać",rule:"znać + сущ. в Biernik.\n«Знаете этот ресторан?» → znać.\n\nZna pan tę restaurację?"},
{q:"Nie ..., o której zaczyna się film.\n(a) znam  (b) wiem",a:"wiem",hint:"информация → wiedzieć",rule:"wiedzieć = информация, факт.\n\nNie wiem, o której... / Nie wiem, kiedy... / Nie wiem, dlaczego..."},
{q:"Czy ... swoich sąsiadów?\n(a) znasz  (b) wiesz",a:"znasz",hint:"знать кого → znać",rule:"znać + лицо (кого?)\n\nZnasz sąsiadów? = Знаешь соседей?\nОбъект — люди → znać."},
{q:"Nie ..., ile to kosztuje.\n(a) znam  (b) wiem",a:"wiem",hint:"wiedzieć + ile",rule:"wiedzieć перед вопросительными словами:\n\nNie wiem, ile kosztuje. (сколько)\nNie wiem, co to znaczy. (что)\nNie wiem, gdzie to jest. (где)"},
{q:"Dobrze ... ten film, widziałem go 3 razy.\n(a) znam  (b) wiem",a:"znam",hint:"знакомство → znać",rule:"znać = быть знакомым с чем-то.\n\nZnam ten film. = Знаком с фильмом.\nZnam to miejsce.\n\nЗнание через опыт → znać."},
{q:"Nie ..., czy ona przyjdzie.\n(a) znam  (b) wiem",a:"wiem",hint:"wiedzieć + czy",rule:"wiedzieć + czy (ли):\n\nNie wiem, czy przyjdzie.\nNie wiem, czy to prawda.\n\nczy = вводит косвенный вопрос → wiedzieć."},
{q:"... dobrze tę okolicę, mieszkam tu 10 lat.\n(a) Znam  (b) Wiem",a:"Znam",hint:"знать место → znać",rule:"znać + место (как объект знакомства):\n\nZnam tę okolicę. (знаю эту местность)\nZnam Kraków bardzo dobrze.\n\nНо: Wiem, gdzie jest Kraków. (информация)"},
{q:"Czy ... , kto to napisał?\n(a) znasz  (b) wiesz",a:"wiesz",hint:"wiedzieć + kto",rule:"wiedzieć + kto/co/jak/gdzie/kiedy:\n\nCzy wiesz, kto to napisał?\nCzy wiesz, co się stało?\n\nВопросительное слово → wiedzieć."},
{q:"Nie ... tego słowa, co ono znaczy?\n(a) znam  (b) wiem",a:"znam",hint:"słowo = объект → znać",rule:"znać + конкретный объект:\n\nNie znam tego słowa. (не знаю это слово)\nNie znam tej piosenki. (не знаю эту песню)\n\nНо: Nie wiem, co to słowo znaczy. (информация)"},
{q:"... swoją wartość i nie dam się wykorzystać.\n(a) Znam  (b) Wiem",a:"Znam",hint:"znać = осознавать",rule:"znać + абстрактное понятие (как объект):\n\nZnam swoją wartość. (знаю свою ценность)\nZnam swoje prawa.\nZnam ryzyko.\n\nОбъект → znać."},
{q:"Nie ..., jak to powiedzieć po polsku.\n(a) znam  (b) wiem",a:"wiem",hint:"wiedzieć + jak",rule:"wiedzieć + jak (как):\n\nNie wiem, jak to powiedzieć.\nNie wiem, jak to zrobić.\n\njak = вопросительное слово → wiedzieć."},
{q:"On dobrze ... swój fach.\n(a) zna  (b) wie",a:"zna",hint:"fach = объект → znać",rule:"znać + область/умение как объект:\n\nZna swój fach. (знает своё ремесло)\nZna się na rzeczy. (разбирается)\n\nОбъект (сущ.) → znać."},
{q:"Nikt nie ..., co będzie jutro.\n(a) zna  (b) wie",a:"wie",hint:"wiedzieć + co",rule:"wiedzieć + co:\n\nNikt nie wie, co będzie jutro.\nNikt nie wie, co się stanie.\n\nco = вопросительное → wiedzieć."}
]},

{id:"narz",icon:"\u{1F527}",title:"Творительный (Narzędnik)",color:"#e36414",cards:[
{q:"Mój brat jest ... ... (początkujący programista)",a:"początkującym programistą",hint:"być + Narz.",rule:"Narzędnik после być:\n\nПрилаг.: -y → -ym\nСущ. муж. на -a: -a → -ą\n\npoczątkujący → początkującym\nprogramista → programistą"},
{q:"Do pracy jadę ... (hulajnoga)",a:"hulajnogą",hint:"-a → -ą",rule:"Narzędnik транспорта (без предлога):\n\nЖен. -a → -ą: hulajnogą, taksówką\nМуж. + -em: tramwajem, autobusem"},
{q:"Latte z ... ... (mleko roślinne)",a:"mlekiem roślinnym",hint:"z + Narz.",rule:"z + Narzędnik = с чем\n\nСр.: -o → -em (mleko → mlekiem)\nПрилаг. ср.: -e → -ym (roślinne → roślinnym)"},
{q:"Jeździlibyście ... (tramwaj)",a:"tramwajem",hint:"транспорт",rule:"Транспорт в Narzędnik:\n\ntramwaj → tramwajem\nautobus → autobusem\nsamochód → samochodem"},
{q:"Interesuję się ... (historia)",a:"historią",hint:"interesować się + Narz.",rule:"interesować się + Narzędnik:\n\nhistoria → historią\ngeografia → geografią\n\nТакже: zajmować się, opiekować się + Narz."},
{q:"Ona jest ... ... (dobra nauczycielka)",a:"dobrą nauczycielką",hint:"жен. Narz.",rule:"Narzędnik жен.:\n\nПрилаг.: -a → -ą (dobra → dobrą)\nСущ. -ka → -ką (nauczycielka → nauczycielką)"},
{q:"Rozmawiam z moim ... (brat)",a:"bratem",hint:"z + муж. -em",rule:"z + Narzędnik муж.:\n\nbrat → bratem\nojciec → ojcem\nprzyjaciel → przyjacielem"},
{q:"Pojechaliśmy tam ... (samolot)",a:"samolotem",hint:"-em",rule:"Транспорт муж.: + -em\n\nsamolot → samolotem\nstatek → statkiem\npociąg → pociągiem"},
{q:"Przed ... (szkoła) stoi autobus",a:"szkołą",hint:"przed + Narz.",rule:"przed + Narzędnik = перед чем:\n\nprzed szkołą, przed domem, przed obiadem\n\nЖен. -a → -ą, Муж. + -em, Ср. -o → -em"},
{q:"Między ... a ... (dom, park)",a:"domem a parkiem",hint:"między + Narz. a Narz.",rule:"między + Narz. a + Narz. = между:\n\nmiędzy domem a parkiem\nmiędzy pracą a domem\n\nМуж.: + -em"},
{q:"Martwię się ... (zdrowie)",a:"zdrowiem",hint:"-ie → -iem",rule:"martwić się + Narzędnik = волноваться о:\n\nzdrowie → zdrowiem\ndziecko → dzieckiem\n\nСр. на -ie: -ie → -iem"},
{q:"Jest ... ... (znany aktor)",a:"znanym aktorem",hint:"być + муж. Narz.",rule:"być + Narzędnik (муж.):\n\nПрилаг.: -y → -ym (znany → znanym)\nСущ. муж.: + -em (aktor → aktorem)\n\nJest znanym aktorem. Jest dobrym lekarzem."},
{q:"Idę na spotkanie z ... (koleżanka Ania)",a:"koleżanką Anią",hint:"z + жен. Narz.",rule:"Имена собственные тоже склоняются:\n\nAnia → Anią, Kasia → Kasią\nkoleżanka → koleżanką\n\nz koleżanką Anią"},
{q:"Kroję chleb ... (nóż)",a:"nożem",hint:"инструмент в Narz.",rule:"Инструмент (чем?) = Narzędnik без предлога:\n\nnóż → nożem\nwidelec → widelcem\nołówek → ołówkiem\n\nKroję nożem. Piszę ołówkiem."},
{q:"Cieszę się ... wynikiem (dobry)",a:"dobrym",hint:"cieszyć się + Narz.",rule:"cieszyć się + Narz. = радоваться чему:\n\ndobry → dobrym\nwynik → wynikiem\n\nCieszę się dobrym wynikiem.\nТакже: cieszyć się życiem, pogodą"},
{q:"Zajmuję się ... (dziecko, мн.ч.)",a:"dziećmi",hint:"мн.ч. Narz. неправ.",rule:"Мн.ч. Narzędnik — неправильные:\n\ndzieci → dziećmi\nludzie → ludźmi\nkonie → końmi\n\nОбычное мн.ч.: + -ami (kotami, psami)"}
]},

{id:"dop",icon:"\u{1F4C9}",title:"Родительный (Dopełniacz)",color:"#d62828",cards:[
{q:"Nie lubię ... ... (mocna kawa)",a:"mocnej kawy",hint:"nie + Dop.",rule:"Dopełniacz после отрицания:\n\nЖен. прилаг.: -a → -ej (mocna → mocnej)\nЖен. сущ.: -a → -y (kawa → kawy)\n\nNie lubię mocnej kawy. Nie mam czasu."},
{q:"brakiem ... na bilety (pieniądze)",a:"pieniędzy",hint:"мн.ч. Dop.",rule:"Dopełniacz мн.ч. неправильные:\n\npieniądze → pieniędzy\ndzieci → dzieci\nludzie → ludzi"},
{q:"Od ... pożyczyłeś? (kto)",a:"kogo",hint:"od + Dop.",rule:"od + Dopełniacz.\n\nkto → kogo\nco → czego\non → niego (после предлога)"},
{q:"Z powodu ... (choroba)",a:"choroby",hint:"z powodu + Dop.",rule:"z powodu + Dop. = из-за (форм.)\n\nchoroba → choroby\ndeszcz → deszczu\n\nСравни: przez + Biernik (разг.)"},
{q:"Nie ma ... ... (troje studentów)",a:"trojga studentów",hint:"troje → trojga",rule:"Собирательные в Dop.:\n\ndwoje → dwojga\ntroje → trojga\nczworo → czworga"},
{q:"Szukam ... ... (nowy telefon)",a:"nowego telefonu",hint:"szukać + Dop.",rule:"szukać + Dop.:\n\nМуж. прилаг.: -y → -ego (nowy → nowego)\nМуж. неодуш.: -∅ → -u (telefon → telefonu)\n\nТакже: potrzebować, unikać, bać się + Dop."},
{q:"Do ... jedzie autobus? (dworzec)",a:"dworca",hint:"-ec → -ca",rule:"do + Dop. = до, к\n\ndworzec → dworca\nojciec → ojca\nchłopiec → chłopca"},
{q:"Nie ma tu ... (woda)",a:"wody",hint:"nie ma + Dop.",rule:"nie ma + Dop. = нет\n\nwoda → wody\nchleb → chleba\nmleko → mleka"},
{q:"Kupiłem butelkę ... (sok pomarańczowy)",a:"soku pomarańczowego",hint:"количество + Dop.",rule:"Количество + Dop.:\n\nsok → soku, pomarańczowy → pomarańczowego\n\nbutelkę soku, szklankę mleka, kilogram cukru"},
{q:"Bez ... (parasol) nie wychodź!",a:"parasola",hint:"bez + Dop.",rule:"bez + Dop. = без\n\nparasol → parasola\ntelefon → telefonu\n\nBez parasola, bez pieniędzy, bez pracy"},
{q:"Naprzeciwko ... (kościół) jest apteka",a:"kościoła",hint:"напротив + Dop.",rule:"naprzeciwko + Dop. = напротив\n\nkościół → kościoła\n\nТак же: obok + Dop., koło + Dop., blisko + Dop."},
{q:"Podczas ... (spotkanie) nie używajcie telefonów",a:"spotkania",hint:"podczas + Dop.",rule:"podczas + Dop. = во время\n\nСр. род: -e → -a (spotkanie → spotkania)\n\npodczas spotkania, podczas lekcji, podczas przerwy"},
{q:"Nie piję ... (alkohol)",a:"alkoholu",hint:"не пить чего → Dop.",rule:"Отрицание + Dop.:\n\nalkohol → alkoholu\nkawa → kawy\n\nНо: Piję kawę. (утверд. → Biernik)"},
{q:"To jest dom ... ... (moja babcia)",a:"mojej babci",hint:"чей? → Dop.",rule:"Dopełniacz принадлежности (чей?):\n\nЖен. прилаг.: -a → -ej (moja → mojej)\nЖен. на -ia: -ia → -i (babcia → babci)"},
{q:"Boisz się ... (pająk, мн.ч.)?",a:"pająków",hint:"bać się + Dop. мн.",rule:"bać się + Dop. = бояться чего:\n\nМн. муж. одуш.: -ów (pająk → pająków)\n\nbać się pająków, psów, egzaminów"},
{q:"Potrzebuję ... (pomoc)",a:"pomocy",hint:"-c → -cy",rule:"potrzebować + Dop.:\n\npomoc → pomocy\nnoc → nocy\nrzecz → rzeczy\n\nЖен. на согласную: + -y/-i"},
{q:"Ile ... (osoba) przyszło na spotkanie?",a:"osób",hint:"ile + Dop. мн.",rule:"ile + Dop. мн.:\n\nosoba → osób (выпадение -o-)\nksiążka → książek\nstudent → studentów\n\nile osób, ile książek, ile studentów"}
]},

{id:"miej",icon:"\u{1F4CD}",title:"Местный (Miejscownik)",color:"#0077b6",cards:[
{q:"Mieszkamy w ... (Szwecja)",a:"Szwecji",hint:"-ja → -ji",rule:"Miejscownik после w, na, o, po, przy.\n\nЖен. -ja → -ji: Szwecja → Szwecji\nЖен. -ka → -ce: Polska → Polsce"},
{q:"Byłam w ... ... (nowa kawiarnia)",a:"nowej kawiarni",hint:"-a → -ej, -nia → -ni",rule:"Miejscownik жен.:\n\nПрилаг.: -a → -ej\nСущ. -nia → -ni (kawiarnia → kawiarni)\n-ka → -ce (apteka → aptece)\n-a → -e (szkoła → szkole)"},
{q:"Parki w moim ... (miasto)",a:"mieście",hint:"st → ści",rule:"Miejscownik ср. — чередования:\n\nmiasto → mieście (st → ści)\nmorze → morzu\npiwo → piwie (w → wi)"},
{q:"Spotkanie o ... ... (08:30)",a:"ósmej trzydzieści",hint:"o + порядк. в Miej.",rule:"Время: o + порядковое в Miej. (жен.):\n\no ósmej = в 8:00\no wpół do dziewiątej = в 8:30\no pierwszej, o drugiej, o trzeciej..."},
{q:"Rozmawialiśmy o ... (pogoda)",a:"pogodzie",hint:"-da → -dzie",rule:"o + Miej. = о чём-то\n\n-da → -dzie: pogoda → pogodzie\n-ta → -cie: robota → robocie\n-ra → -rze: literatura → literaturze"},
{q:"Mieszkam na ... ... (trzecie piętro)",a:"trzecim piętrze",hint:"ср. Miej.",rule:"na + Miej.:\n\nСр. прилаг.: -ie → -im\nСр. сущ.: -o → -e (piętro → piętrze)\n\nna trzecim piętrze, na dużym biurku"},
{q:"Jestem teraz w ... (Kraków)",a:"Krakowie",hint:"-ów → -owie",rule:"Города в Miej.:\n\nKraków → Krakowie\nWrocław → Wrocławiu\nGdańsk → Gdańsku\nWarszawa → Warszawie"},
{q:"Opowiadał o swojej ... (podróż)",a:"podróży",hint:"-ż → -ży",rule:"Жен. на согласную:\n\npodróż → podróży\nnoc → nocy\nmiłość → miłości"},
{q:"Spotkamy się przy ... (fontanna)",a:"fontannie",hint:"-nna → -nnie",rule:"przy + Miej. = у, около:\n\nfontanna → fontannie (nn → nni + e)\n\nprzy fontannie, przy stacji, przy dworcu"},
{q:"Myślę o ... ... (mój syn)",a:"moim synu",hint:"o + муж. Miej.",rule:"Miej. муж.:\n\nПрилаг.: -ój → -oim (mój → moim)\nСущ.: + -u (syn → synu)"},
{q:"Kwiaty na ... (balkon)",a:"balkonie",hint:"муж. + -ie",rule:"Miej. муж. — окончания:\n\n-∅ → -ie (balkon → balkonie)\n-∅ → -u (park → parku)\n\nТвёрдые → -ie с чередованием, мягкие → -u часто"},
{q:"Po ... (obiad) poszliśmy na spacer",a:"obiedzie",hint:"po + Miej., чередование",rule:"po + Miej. = после:\n\nobiad → obiedzie (a → e, d → dzi)\nśniadanie → śniadaniu\nkolacja → kolacji"},
{q:"W ... (ten sklep) jest promocja",a:"tym sklepie",hint:"ten → tym",rule:"Указательные в Miej.:\n\nten → tym (муж./ср.)\nta → tej (жен.)\nci/te → tych (мн.)\n\nw tym sklepie, w tej szkole"},
{q:"Dużo mówi się o ... (zdrowie)",a:"zdrowiu",hint:"ср. -ie → -iu",rule:"Ср. на -ie в Miej.:\n\nzdrowie → zdrowiu\nżycie → życiu\nzdanie → zdaniu\n\no zdrowiu, o życiu, w zdaniu"},
{q:"Byłem na ... (lotnisko)",a:"lotnisku",hint:"ср. -ko → -ku",rule:"Ср. на -ko, -go, -cho в Miej. → -ku:\n\nlotnisko → lotnisku\njabłko → jabłku\nucho → uchu"},
{q:"W ... (ta książka) jest ciekawy rozdział",a:"tej książce",hint:"жен. -ka → -ce",rule:"Жен. на -ka → -ce в Miej.:\n\nksiążka → książce\nręka → ręce\nnoga → nodze (-ga → -dze)\n\nw tej książce, na mojej ręce"}
]},

{id:"cel",icon:"\u{1F3AF}",title:"Дательный (Celownik)",color:"#4361ee",cards:[
{q:"Sara napisała ... (ja) co się wydarzyło",a:"mi",hint:"кому? → mi",rule:"Celownik — кому?\n\nja → mi/mnie\nty → ci/tobie\non → mu/jemu\nona → jej\nmy → nam\nwy → wam\noni → im\n\nmi — короткая, mnie — полная."},
{q:"Ufam moim ... (przyjaciel, мн.ч.)",a:"przyjaciołom",hint:"-om",rule:"Celownik мн.ч.: -om для всех:\n\nprzyjaciel → przyjaciołom\nstudent → studentom\ndziecko → dzieciom"},
{q:"Świat był przeciwko ... (ty)",a:"tobie",hint:"przeciwko + Cel.",rule:"przeciwko + Cel.:\n\nprzeciwko mnie, tobie, niemu\n\nПосле предлогов — полные формы."},
{q:"Film bardzo mi się ... (podobać, on)",a:"podoba",hint:"podobać się + Cel.",rule:"podobać się + Cel. = нравиться кому:\n\nFilm mi się podoba.\nTo ci się nie spodoba.\n\nГлагол согласуется с подлежащим."},
{q:"Kupiłem ... (ona) kwiaty",a:"jej",hint:"кому? → jej",rule:"Cel. 3 лица:\n\non → mu/jemu\nona → jej/niej\noni → im/nim"},
{q:"Pomagam ... (moja siostra)",a:"mojej siostrze",hint:"pomagać + Cel.",rule:"pomagać + Cel.:\n\nmoja → mojej, siostra → siostrze (r→rz)\n\npomagam mojej siostrze, mojemu bratu"},
{q:"Daj ... (my) znać, kiedy przyjedziesz",a:"nam",hint:"dać + Cel.",rule:"dać + Cel.:\n\nmy → nam, wy → wam\n\nТакже + Cel.: powiedzieć, wysłać, obiecać."},
{q:"Gratuluję ... (ty) nowej pracy!",a:"ci",hint:"gratulować + Cel.",rule:"gratulować + Cel. = поздравлять кого:\n\nty → ci (короткая)\n\nGratuluję ci! Gratuluję wam!"},
{q:"Nie przeszkadzaj ... (ja)!",a:"mi",hint:"przeszkadzać + Cel.",rule:"przeszkadzać + Cel. = мешать кому:\n\nNie przeszkadzaj mi!\nHałas mu przeszkadza."},
{q:"Dziecko → ... jest ciemno (Cel.)",a:"dziecku",hint:"ср. род Cel. -u",rule:"Безличные + Cel.:\n\ndziecko → dziecku\n\nDziecku jest zimno.\nMi jest smutno.\nJej jest wstyd."},
{q:"Życzę ... (pan) wszystkiego najlepszego!",a:"panu",hint:"pan → panu в Cel.",rule:"Вежливая форма в Cel.:\n\npan → panu\npani → pani (не меняется!)\n\nŻyczę panu zdrowia!"},
{q:"Opowiedz ... (oni) o wakacjach",a:"im",hint:"oni → im",rule:"Cel. 3 мн.ч.:\n\noni/one → im (короткая) / nim (после предлога)\n\nOpowiedz im. Daj im znać.\nПосле предл.: ku nim, dzięki nim"},
{q:"Dzięki ... (wy) udało się!",a:"wam",hint:"dzięki + Cel.",rule:"dzięki + Cel. = благодаря:\n\ndzięki wam, dzięki tobie, dzięki nam\n\nТакже: dzięki Bogu, dzięki pogodzie"},
{q:"Obiecałem ... (moja mama), że wrócę wcześnie",a:"mojej mamie",hint:"Cel. жен. -a → -ie",rule:"Cel. жен.:\n\nmoja → mojej\nmama → mamie (-a → -ie)\n\nТак же: kobieta → kobiecie, siostra → siostrze"},
{q:"Jest ... (ja) wszystko jedno",a:"mi",hint:"безличное + Cel.",rule:"Безличные выражения + Cel.:\n\nJest mi wszystko jedno. (мне всё равно)\nJest mi zimno. (мне холодно)\nJest mi wstyd. (мне стыдно)\nZależy mi na tym. (мне это важно)"}
]},

{id:"past",icon:"⏪",title:"Прошедшее время",color:"#6a040f",cards:[
{q:"Wczoraj dzieci ... bajki (oglądać)",a:"oglądały",hint:"dzieci → -ły",rule:"Прошедшее — окончания рода:\n\nМуж.: -ł\nЖен.: -ła\nСр.: -ło\nЛич.-муж. мн.: -li\nОст. мн.: -ły\n\ndzieci = нелич.-муж. → -ły"},
{q:"Moi dziadkowie ... się w 1965\n(a) pobrali  (b) ożenili  (c) wyszli za mąż",a:"pobrali",hint:"пара → pobrać się",rule:"pobrać się = пожениться (пара)\nożenić się = жениться (мужчина)\nwyjść za mąż = замуж (женщина)"},
{q:"Na czele urzędu ... Julia Nowak (stanąć)",a:"stanęła",hint:"-ąć → она -ęła",rule:"Глаголы на -ąć:\n\non → stanął\nona → stanęła\noni → stanęli\none → stanęły"},
{q:"Od kiedy ... nowy most (zbudować)",a:"zbudowano",hint:"-no/-to",rule:"Безличная форма (-no/-to):\n\n-ać → -ano: zbudowano\n-ić → -ono: zrobiono\n-ąć → -ęto: wzięto"},
{q:"Mama ... pyszny obiad (ugotować)",a:"ugotowała",hint:"жен. → -ała",rule:"Совершенный вид жен.:\n\nugotować → ugotowała\nnapisać → napisała\nkupić → kupiła"},
{q:"Chłopcy ... do szkoły (biec)",a:"biegli",hint:"лич.-муж. → -li",rule:"biec в прошедшем:\n\non → biegł\nona → biegła\noni → biegli"},
{q:"My ... w parku (siedzieć, смеш. группа)",a:"siedzieliśmy",hint:"my лич.-муж. → -liśmy",rule:"Окончания лица:\n\nja → -łem/-łam\nty → -łeś/-łaś\nmy → -liśmy/-łyśmy"},
{q:"W zeszłym roku ... do Włoch (jechać, ja муж.)",a:"jechałem",hint:"-łem",rule:"ja муж.: -łem (jechałem)\nja жен.: -łam (jechałam)"},
{q:"Ona ... dużo pieniędzy (wydać)",a:"wydała",hint:"wydać → wydała",rule:"wydać (потратить):\n\non → wydał\nona → wydała\noni → wydali\none → wydały"},
{q:"Psy ... po podwórku (biegać)",a:"biegały",hint:"psy = нелич.-муж. → -ły",rule:"Животные = нелично-мужская форма:\n\npsy → biegały (не biegali!)\nkoty → spały\n\nТолько мужчины-люди → -li"},
{q:"Kto ... moje klucze? (wziąć)",a:"wziął",hint:"wziąć → wziął",rule:"wziąć в прошедшем:\n\non → wziął\nona → wzięła\noni → wzięli"},
{q:"Wczoraj ... do 23:00 (pracować, ja жен.)",a:"pracowałam",hint:"ja жен. → -łam",rule:"Ja жен.: -łam: pracowałam\nJa муж.: -łem: pracowałem"},
{q:"... deszcz i ... wiatr (padać, wiać)",a:"padał, wiał",hint:"муж. ед. → -ł",rule:"Погода — 3 лицо ед. муж.:\n\ndeszcz (муж.) → padał\nwiatr (муж.) → wiał"},
{q:"Czy ... (wy, жен.) już na tym filmie?",a:"byłyście",hint:"wy жен. → -łyście",rule:"Vy нелич.-муж. формы:\n\nwy (с мужчинами) → byliście\nwy (без мужчин) → byłyście\n\n-liście / -łyście"},
{q:"Samochód ... (stać) na parkingu przez tydzień",a:"stał",hint:"муж. → -ł",rule:"Неодушевлённые предметы — по грамм. роду:\n\nsamochód (муж.) → stał\nksiążka (жен.) → leżała\nradio (ср.) → grało"},
{q:"Wszystko ... się dobrze (skończyć)",a:"skończyło",hint:"wszystko = ср. → -ło",rule:"wszystko (ср. род) → -ło:\n\nWszystko skończyło się dobrze.\nTo wydarzyło się wczoraj.\nMleko skwaśniało."}
]},

{id:"cond",icon:"\u{1F4AD}",title:"Условное + żeby",color:"#457b9d",cards:[
{q:"Gdybyście mieli kartę, ... tramwajem (jeździć, wy)",a:"jeździlibyście",hint:"прош. + byście",rule:"Условное = прош. + by + лицо:\n\nja → -łbym / -łabym\nty → -łbyś / -łabyś\nmy → -libyśmy\nwy → -libyście"},
{q:"Proszę, żebyś ... ze mną (pójść, ty)",a:"poszedł/poszła",hint:"żebyś + прош.",rule:"żeby + лицо + прош. время:\n\nżebym (ja), żebyś (ty), żeby (on)\nżebyśmy (my), żebyście (wy)"},
{q:"Chciałby, ... (my) częściej spotykali się",a:"żebyśmy",hint:"żeby+śmy",rule:"Окончания к żeby:\n\nżebym, żebyś, żeby\nżebyśmy, żebyście, żeby"},
{q:"Gdybym ... czas, ... nad morze (mieć/pojechać, ja м.)",a:"miał, pojechałbym",hint:"gdybym + прош., -łbym",rule:"Полная конструкция:\n\ngdybym miał czas, pojechałbym\n= если бы было время, поехал бы"},
{q:"Chcielibyśmy ... pizzę (zamówić)",a:"zamówić",hint:"условное + инфинитив",rule:"Условное + инфинитив:\n\nChcielibyśmy zamówić = хотели бы заказать\nChciałbym kupić = хотел бы купить"},
{q:"Wolał, żeby nikt o tym nie ... (wiedzieć)",a:"wiedział",hint:"żeby + 3 ед.",rule:"żeby + 3 лицо (без окончания):\n\nżeby nikt nie wiedział\nżeby nic się nie zmieniło"},
{q:"Na twoim miejscu ... do lekarza (pójść, ja ж.)",a:"poszłabym",hint:"na twoim miejscu = условное",rule:"Na twoim miejscu + условное:\n\nNa twoim miejscu poszłabym do lekarza.\n= На твоём месте я бы пошла к врачу."},
{q:"Gdyby ... (padać) deszcz, ... (zostać, my) w domu",a:"padał, zostalibyśmy",hint:"gdyby + прош., -libyśmy",rule:"Gdyby padał deszcz, zostalibyśmy w domu.\n= Если бы шёл дождь, мы бы остались."},
{q:"Czy mógł... mi pan pomóc? (вежл. просьба)",a:"mógłby",hint:"мог бы = mógłby",rule:"Вежливая просьба с условным:\n\nCzy mógłby mi pan pomóc?\nmógłby (он), mogłaby (она)"},
{q:"Powiedziała, ... (ja м.) zadzwonił wieczorem",a:"żebym",hint:"żeby + m = żebym",rule:"Косвенная речь с żeby:\n\nPowiedziała, żebym zadzwonił.\n= Она сказала, чтобы я позвонил."},
{q:"... pieniądze, kupiłbym nowy laptop (mieć, gdybym)",a:"Gdybym miał",hint:"gdybym + прош.",rule:"Gdybym + прош. время:\n\nGdybym miał pieniądze... = Если бы у меня были деньги...\nGdybym wiedział... = Если бы я знал..."},
{q:"Chciałabym, żeby ... (on) częściej dzwonił",a:"żeby",hint:"3 лицо = żeby без окончания",rule:"3 лицо (on/ona) = просто żeby:\n\nChciałabym, żeby dzwonił.\nProszę, żeby przyszedł.\n\nНет личного окончания в 3 лице!"},
{q:"Byłoby miło, gdybyś ... (przyjść)",a:"przyszedł/przyszła",hint:"gdybyś + прош.",rule:"gdybyś + прош. = если бы ты:\n\ngdybyś przyszedł (м.) / przyszła (ж.)\ngdybyś mógł / mogła\ngdybyś chciał / chciała"},
{q:"Zrobiłbym to, ... (ale, mieć, czas, nie)",a:"ale nie miałbym czasu",hint:"ale nie + условное",rule:"Условное в отрицании:\n\nnie + условное:\nnie miałbym = не имел бы\nnie zrobiłabym = не сделала бы\nnie poszlibyśmy = не пошли бы"}
]},

{id:"ktory",icon:"\u{1F517}",title:"Который (który)",color:"#52796f",cards:[
{q:"Ludzie, ... jedzą zdrowo (który, лич.-муж.)",a:"którzy",hint:"лич.-муж. мн.",rule:"który по родам и числам:\n\nМуж.: który\nЖен.: która\nСр.: które\nЛич.-муж. мн.: którzy\nОст. мн.: które"},
{q:"Osoby, ... tego nie robią (który, жен. мн.)",a:"które",hint:"немуж. мн.",rule:"osoby = жен. мн. → które\n\nДаже о мужчинах — osoby грамм. женский."},
{q:"Mężczyzna, ... tu mieszka (który)",a:"który",hint:"муж. ед. имен.",rule:"który в именительном (подлежащее):\n\nmężczyzna → który\nkobieta → która\ndziecko → które"},
{q:"Film, ... wczoraj oglądałem (который, Biernik)",a:"który",hint:"муж. неодуш. B.=M.",rule:"Biernik муж. неодуш. = Mianownik:\n\nfilm → który (B.=M.)\n\nНо одуш.: mężczyzna, którego spotkałem (B.=Dop.)"},
{q:"Kobieta, z ... rozmawiałem (Narzędnik)",a:"którą",hint:"жен. Narz. = którą",rule:"który в Narzędnik:\n\nЖен.: którą\nМуж.: którym\nМн.: którymi"},
{q:"Sklep, w ... kupuję chleb (Miejscownik)",a:"którym",hint:"муж. Miej. = którym",rule:"który в Miejscownik:\n\nМуж./ср.: którym\nЖен.: której\nМн.: których"},
{q:"Dziecko, ... widziałem w parku (Biernik)",a:"które",hint:"ср. B.=M.",rule:"Ср. род Biernik = Mianownik:\n\ndziecko → które (B.=M.)"},
{q:"Przyjaciel, ... (Celownik) pożyczyłem książkę",a:"któremu",hint:"муж. Cel. = któremu",rule:"który в Celownik:\n\nМуж./ср.: któremu\nЖен.: której\nМн.: którym"},
{q:"Studenci, o ... mówił profesor (Miej. мн.)",a:"których",hint:"мн. Miej. = których",rule:"Мн.ч. Miejscownik:\n\nktórzy/które → których"},
{q:"Dom, obok ... (Dop.) jest park",a:"którego",hint:"муж. Dop. = którego",rule:"który в Dopełniacz:\n\nМуж./ср.: którego\nЖен.: której\nМн.: których"},
{q:"To jest kobieta, ... (Dop.) szukamy",a:"której",hint:"жен. Dop. = której",rule:"Dop. жен. = której:\n\nkobieta, której szukamy\nkobieta, której nie znam\n\nТакже = Miej. жен.: o której mówię"},
{q:"Chłopiec, ... (Biernik одуш.) spotkałem",a:"którego",hint:"одуш. B.=Dop.",rule:"Biernik муж. одуш. = Dopełniacz:\n\nchłopiec → którego (B.=D.)\nfilm → który (B.=M., неодуш.)\n\nОдуш. vs неодуш. — ключевое отличие!"},
{q:"Kraje, do ... (Dop. мн.) chcemy pojechać",a:"których",hint:"мн. Dop. = których",rule:"Мн.ч. Dopełniacz = których:\n\ndo których, bez których, dla których\n\nOдинаково для всех родов во мн.ч."},
{q:"Dziewczyna, ... (Cel.) dałem prezent",a:"której",hint:"жен. Cel. = której",rule:"Celownik жен. = której:\n\ndziewczyna, której dałem prezent\nkobieta, której pomogłem\n\nСовпадает с Dop. жен. (której)!"}
]},

{id:"comp",icon:"⚖️",title:"Степени сравнения",color:"#bc6c25",cards:[
{q:"Amazonka jest ... rzeką niż Wisła (długi)",a:"dłuższą",hint:"długi → dłuższy",rule:"Сравнительная:\n\ndługi → dłuższy\nkrótki → krótszy\ndobry → lepszy\nzły → gorszy\n\nrzeką (жен. Narz.) → dłuższą"},
{q:"Piotr gra ... z całej grupy (dobrze, превосх.)",a:"najlepiej",hint:"→ lepiej → najlepiej",rule:"Наречия:\n\ndobrze → lepiej → najlepiej\nźle → gorzej → najgorzej\ndużo → więcej → najwięcej"},
{q:"Jej koledzy są bardzo ... (miły, лич.-муж.)",a:"mili",hint:"ł → l",rule:"Лич.-муж. мн. — чередования:\n\nmiły → mili (ł→l)\ndobry → dobrzy (r→rz)\nwysoki → wysocy (k→c)"},
{q:"Ten dom jest ... od tamtego (duży)",a:"większy",hint:"неправильная форма",rule:"Неправильные:\n\nduży → większy → największy\nmały → mniejszy → najmniejszy\ndobry → lepszy → najlepszy\nzły → gorszy → najgorszy"},
{q:"Marta biega ... niż Ola (szybko)",a:"szybciej",hint:"-ko → -ciej",rule:"Наречия на -ko:\n\nszybko → szybciej\nwolno → wolniej\ncicho → ciszej"},
{q:"To ... restauracja w mieście (dobry, прев. жен.)",a:"najlepsza",hint:"najlepszy жен. -a",rule:"Превосходная по родам:\n\nМуж.: najlepszy\nЖен.: najlepsza\nСр.: najlepsze"},
{q:"Im ..., tym lepiej (dużo)",a:"więcej",hint:"im + сравн., tym + сравн.",rule:"im... tym... = чем... тем...:\n\nim więcej, tym lepiej\nim starszy, tym mądrzejszy"},
{q:"On jest ... (wysoki) niż jego brat",a:"wyższy",hint:"wysoki → wyższy",rule:"Прилагательные с чередованием:\n\nwysoki → wyższy (k→ż+sz)\nniski → niższy\nszeroki → szerszy"},
{q:"Ta książka jest ... (ciekawy) od tamtej",a:"ciekawsza",hint:"жен. -sza",rule:"Регулярное: ciekawy → ciekawszy / ciekawsza\nładny → ładniejszy / ładniejsza"},
{q:"To ... (mały) mieszkanie w tym budynku",a:"najmniejsze",hint:"ср. род превосх.",rule:"Превосходная ср. рода:\n\nmały → mniejszy → najmniejszy\nСр.: najmniejsze"},
{q:"Dziś jest ... (zimno) niż wczoraj",a:"zimniej",hint:"-no → -niej",rule:"Наречия на -no:\n\nzimno → zimniej\nciepło → cieplej\nciemno → ciemniej\njasno → jaśniej"},
{q:"To jest ... (stary) kościół w Polsce",a:"najstarszy",hint:"превосх. муж.",rule:"stary → starszy → najstarszy\n\nnajstarszy kościół = самый старый костёл\n\nТак же: młody → młodszy → najmłodszy"},
{q:"Ten egzamin był ... (trudny) niż poprzedni",a:"trudniejszy",hint:"-ny → -niejszy",rule:"Регулярное -ny → -niejszy:\n\ntrudny → trudniejszy\nładny → ładniejszy\nsmaczny → smaczniejszy\nważny → ważniejszy"},
{q:"Mówi po polsku coraz ... (dobrze)",a:"lepiej",hint:"coraz + сравн.",rule:"coraz + сравнительная = всё более:\n\ncoraz lepiej = всё лучше\ncoraz szybciej = всё быстрее\ncoraz trudniej = всё труднее"}
]},

{id:"num",icon:"\u{1F522}",title:"Числительные",color:"#6d6875",cards:[
{q:"74 − 23 = ? (словами)",a:"pięćdziesiąt jeden",hint:"50+1",rule:"Десятки:\n50 pięćdziesiąt, 60 sześćdziesiąt,\n70 siedemdziesiąt, 80 osiemdziesiąt\n\n74 − 23 = 51 = pięćdziesiąt jeden"},
{q:"1956 год (w ... roku)",a:"tysiąc dziewięćset pięćdziesiątym szóstym",hint:"Miej. порядкового",rule:"Годы: w + Miej. порядкового:\n\nСклоняется только последняя часть:\n1956 = tysiąc dziewięćset pięćdziesiątym szóstym"},
{q:"Mają ... dzieci (3, собират.)",a:"troje",hint:"дети → собирательное",rule:"Собирательные:\n2 = dwoje, 3 = troje, 4 = czworo, 5 = pięcioro\n\ntroje dzieci (не *trzy dzieci!)"},
{q:"Film od ... (12 lat)",a:"dwunastu lat",hint:"od + Dop.",rule:"Числительные 11-19 в Dop.:\n\n11 = jedenastu\n12 = dwunastu\n13 = trzynastu"},
{q:"Zamówiłem ... (2) piwa",a:"dwa",hint:"ср. род → dwa",rule:"Числительные по родам (2):\n\nМуж. лич.: dwóch/dwaj\nМуж. нелич./ср.: dwa\nЖен.: dwie"},
{q:"W pokoju jest ... (5) krzeseł",a:"pięć",hint:"5+ → pięć + Dop. мн.",rule:"5+ → + Dop. мн.:\n\npięć krzeseł, sześć osób, dziesięć minut\n\n2-4 + Mian. мн.: dwa krzesła"},
{q:"Za ... minut (15) będziemy na miejscu",a:"piętnaście",hint:"za + Biernik",rule:"za + Biernik = через:\n\nza piętnaście minut\nza godzinę\nza dwa dni"},
{q:"Mam ... (4) koty",a:"cztery",hint:"2-4 + Mian. мн.",rule:"Числительные 2-4 + Mianownik мн.:\n\ndwa koty, trzy koty, cztery koty\n\nНо 5+: pięć kotów (Dop. мн.)"},
{q:"Potrzebuję ... (100) złotych",a:"stu",hint:"100 в Dop. = stu",rule:"sto (100) по падежам:\n\nMian.: sto\nDop.: stu\nBiernik: sto\nNarz.: stu\nMiej.: stu"},
{q:"Przyjdę za ... (1) godzinę",a:"jedną",hint:"жен. Biernik = jedną",rule:"jeden по родам в Biernik:\n\nМуж. одуш.: jednego\nЖен.: jedną\nСр.: jedno"},
{q:"Zapłaciłem ... (200) złotych",a:"dwieście",hint:"200 = dwieście",rule:"Сотни:\n100 = sto, 200 = dwieście\n300 = trzysta, 400 = czterysta\n500 = pięćset"},
{q:"Na koncercie było ... (1000) osób",a:"tysiąc",hint:"tysiąc + Dop. мн.",rule:"tysiąc = 1000\n\ntysiąc + Dop. мн.:\ntysiąc osób, tysiąc złotych\n\ndwa tysiące (2000), pięć tysięcy (5000)"},
{q:"Mam ... (22) lata",a:"dwadzieścia dwa",hint:"22 + Mian. мн.",rule:"Возраст — числительные:\n\n1 rok, 2/3/4 lata, 5+ lat\n\n22 lata (2-4 на конце → lata)\n25 lat (5+ на конце → lat)"},
{q:"To kosztuje ... (31) złotych",a:"trzydzieści jeden",hint:"31 zlotych",rule:"Валюта — числительные:\n\n1 złoty, 2/3/4 złote, 5+ złotych\n\n31 złotych (1 на конце, но > 20 → złotych)"},
{q:"Na parkingu stoi ... (3) autobusy",a:"trzy",hint:"2-4 + Mian. мн.",rule:"2-4 + Mianownik мн.:\n\ntrzy autobusy, dwa samochody\n\nНо: pięć autobusów (5+ → Dop. мн.)"}
]},

{id:"idiom",icon:"\u{1F4AC}",title:"Идиомы и лексика",color:"#5a189a",cards:[
{q:"Kasia ma świetne pomysły — ma ...\n(a) głowę na karku  (b) pstro w głowie",a:"głowę na karku",hint:"смекалистая",rule:"głowę na karku = смекалистый, с головой.\npstro w głowie = легкомысленный."},
{q:"Zarabia mało. Pracuje ...\n(a) za pół darmo  (b) na czarno  (c) jak szalony",a:"za pół darmo",hint:"за копейки",rule:"za pół darmo = за копейки.\nna czarno = нелегально.\njak szalony = очень много."},
{q:"Ma 15 kg ...\n(a) nadwagi  (b) wagi  (c) przewagi",a:"nadwagi",hint:"лишний вес",rule:"nadwaga = лишний вес\nwaga = вес (нейтрально)\nprzewaga = преимущество"},
{q:"Wysyłam serdeczne ... z wakacji\n(a) witania  (b) pozdrowienia  (c) życzenia",a:"pozdrowienia",hint:"приветы с отдыха",rule:"pozdrowienia = приветы\nżyczenia = пожелания (праздник)"},
{q:"Niczego się nie ...\n(a) przerobił  (b) dorobił  (c) zrobił",a:"dorobił",hint:"нажить",rule:"dorobić się = нажить\nprzerobić = переделать\nzrobić = сделать"},
{q:"Lena ma ... zdać egzamin (nadzieja)",a:"nadzieję",hint:"mieć nadzieję",rule:"mieć nadzieję = надеяться\n\nnadzieja → nadzieję (Biernik: -a → -ę)"},
{q:"Nie mam ... na spacer (ochota)",a:"ochoty",hint:"nie mieć + Dop.",rule:"Отрицание + Dop.:\n\nMam ochotę (утв., Biernik)\nNie mam ochoty (отр., Dop.)"},
{q:"Nie ma ... (pojęcie), co robić",a:"pojęcia",hint:"nie mieć pojęcia",rule:"nie mieć pojęcia = не иметь понятия\n\npojęcie → pojęcia (Dop.)"},
{q:"Wzięli sprawy w swoje ...\n(a) ręce  (b) ręki  (c) rękę",a:"ręce",hint:"в свои руки",rule:"wziąć w swoje ręce = взять в руки\n\nręce = мн.ч. Biernik (=Mian.)"},
{q:"On zawsze ... z siebie\n(a) robi  (b) robi się  (c) robi sobie",a:"robi",hint:"строить из себя",rule:"robić z siebie (głupka/bohatera) = строить из себя"},
{q:"To mi ... w grę!\n(a) nie wchodzi  (b) nie wejdzie  (c) nie wchodzą",a:"nie wchodzi",hint:"не обсуждается",rule:"nie wchodzić w grę = не обсуждается\n\nTo nie wchodzi w grę!"},
{q:"Mam tego ...!\n(a) dosyć  (b) dość  (c) оба верны",a:"оба верны",hint:"dosyć = dość",rule:"dosyć / dość = довольно, хватит\n\nMam tego dosyć! = Mam tego dość!"},
{q:"Nie warto robić z ... widły\n(a) igły  (b) igłą  (c) igłę",a:"igły",hint:"z + Dop.",rule:"robić z igły widły = делать из мухи слона\n\nz + Dop.: igła → igły"},
{q:"Życzę ... ... (ty, powodzenie)!",a:"ci powodzenia",hint:"życzyć + Cel. + Dop.",rule:"życzyć + Cel. (кому) + Dop. (чего):\n\nty → ci, powodzenie → powodzenia"},
{q:"Nie mogę się ... (zdecydować)\n(a) zdecydować  (b) decydować  (c) оба",a:"zdecydować",hint:"nie móc + сов. вид",rule:"nie móc + инфинитив (чаще соверш.):\n\nNie mogę się zdecydować.\n= Не могу решиться.\n\nzdecydować = сов., decydować = несов."},
{q:"Muszę to ... do jutra (zrobić / robić)",a:"zrobić",hint:"musieć + сов. вид",rule:"musieć + инфинитив (чаще соверш.):\n\nMuszę to zrobić = Должен сделать (результат)\nMuszę to robić = Должен делать (процесс)\n\nДо дедлайна → совершенный вид"},
{q:"Daj ... (spokój)! Zostaw mnie!\n(a) spokój  (b) spokoju  (c) spokojem",a:"spokój",hint:"daj + Biernik",rule:"dać + Biernik:\n\nDaj spokój! = Оставь в покое! / Да ладно!\n\nspokój (муж. неодуш.) B. = M. = spokój"}
]},

{id:"po",icon:"⏭️",title:"po + причастия / предлоги",color:"#3a5a40",cards:[
{q:"Zaczniemy wakacje po ... egzaminów (zdać)",a:"zdaniu",hint:"po + Miej.",rule:"po + отглагольное сущ. в Miej.:\n\nzdać → zdanie → po zdaniu\nskończyć → skończenie → po skończeniu"},
{q:"Przyszedł spóźniony, ale ... (uczesać się)",a:"uczesany",hint:"причастие",rule:"Причастие = состояние:\n\nuczesać → uczesany\nspóźnić się → spóźniony\nzmęczyć się → zmęczony"},
{q:"Ona mówi, że to przez ... (on)",a:"niego",hint:"через + Biernik",rule:"przez + B. (виновник), предлог → n-:\n\non → niego (не go!)\nona → nią (не ją!)"},
{q:"Jestem ... po pracy (zmęczyć się)",a:"zmęczony/zmęczona",hint:"быть + причастие",rule:"być + причастие:\n\nzmęczony/zmęczona\nzajęty/zajęta\nzdenerwowany/a"},
{q:"Po ... filmu poszliśmy do domu (obejrzeć)",a:"obejrzeniu",hint:"po + Miej.",rule:"po + отглагольное:\n\nobejrzeć → obejrzenie → po obejrzeniu\nzjeść → zjedzenie → po zjedzeniu"},
{q:"Drzwi są ... (zamknąć)",a:"zamknięte",hint:"мн. причастие -ęte",rule:"Причастия от -ąć:\n\nzamknąć → zamknięty/a/e\nwziąć → wzięty/a/e"},
{q:"List jest ... po polsku (napisać)",a:"napisany",hint:"-ać → -any",rule:"Причастия от -ać → -any:\n\nnapisać → napisany\nprzeczytać → przeczytany\nzrobić → zrobiony (-ić → -ony)"},
{q:"Obiad już ... (ugotować, причастие)",a:"ugotowany",hint:"-ować → -owany",rule:"Причастия от -ować → -owany:\n\nugotować → ugotowany\nzorganizować → zorganizowany"},
{q:"Po ... (przyjść) do domu od razu poszedł spać",a:"przyjściu",hint:"po + przyjście → przyjściu",rule:"Отглагольные от идти:\n\nprzyjść → przyjście → po przyjściu\nwyjść → wyjście → po wyjściu"},
{q:"Jestem ... (zainteresować) tą ofertą",a:"zainteresowany/zainteresowana",hint:"-ować → -owany",rule:"Причастие-прилагательное:\n\nzainteresowany = заинтересованный\nzaskoczony = удивлённый\nzmęczony = уставший"},
{q:"Samochód jest ... (naprawić)",a:"naprawiony",hint:"-ić → -ony",rule:"Причастия от -ić → -ony:\n\nnaprawić → naprawiony\nkupić → kupiony\nzrobić → zrobiony\n\nSamochód jest naprawiony."},
{q:"Sklep jest ... (otworzyć) od 9:00",a:"otwarty",hint:"неправильное причастие",rule:"Неправильные причастия:\n\notworzyć → otwarty (не *otworzony!)\nzakryć → zakryty\nodkryć → odkryty\n\nSklep jest otwarty od 9:00."},
{q:"Po ... (wstać) zrobiłam kawę",a:"wstaniu",hint:"po + wstanie → wstaniu",rule:"po + Miej. от отглагольного:\n\nwstać → wstanie → po wstaniu\nzjeść → zjedzenie → po zjedzeniu\nwypiciu kawy = после кофе"},
{q:"Jestem ... (rozczarować) wynikiem",a:"rozczarowany/rozczarowana",hint:"-ować → -owany + Narz.",rule:"Причастие + Narzędnik (чем?):\n\nrozczarowany wynikiem = разочарован результатом\nzadowolony pracą = доволен работой\nzachwycony filmem = восхищён фильмом"}
]}
];

// Лекции из учебника — отдельная секция
var L=[
{id:"lek5",icon:"📖",title:"Lekcja 5 — Co lubisz robić?",color:"#00838f",cards:[
// ===== PODRĘCZNIK Ćw.1: Словарь хобби =====
{q:"Как по-польски: бегать",a:"biegać",hint:"спорт",rule:"biegać = бегать\npływać = плавать\nuprawiać sport = заниматься спортом"},
{q:"Как по-польски: плавать",a:"pływać",hint:"вода",rule:"pływać = плавать\npływać w basenie / w morzu"},
{q:"Как по-польски: кататься на велосипеде",a:"jeździć na rowerze",hint:"jeździć na + Miej.",rule:"jeździć na + Miejscownik:\nna rowerze, na nartach, na snowboardzie"},
{q:"Как по-польски: кататься на лыжах",a:"jeździć na nartach",hint:"jeździć na + Miej.",rule:"jeździć na nartach = кататься на лыжах"},
{q:"Как по-польски: ходить по горам",a:"chodzić po górach",hint:"chodzić po + Miej.",rule:"chodzić po + Miejscownik:\npo górach, po mieście"},
{q:"Как по-польски: играть на гитаре",a:"grać na gitarze",hint:"grać na + Miej.",rule:"grać na + Miejscownik (инструмент):\nna gitarze, na saksofonie, na pianinie"},
{q:"Как по-польски: играть в теннис",a:"grać w tenisa",hint:"grać w + Biernik",rule:"grać w + Biernik (спорт/игра):\nw tenisa, w karty, w piłkę nożną, w szachy"},
{q:"Как по-польски: слушать музыку",a:"słuchać muzyki",hint:"słuchać + Dop.!",rule:"słuchać + Dopełniacz:\nsłuchać muzyki (не *muzykę!)\nsłuchać radia"},
{q:"Как по-польски: танцевать",a:"tańczyć",hint:"II спр.",rule:"tańczyć = танцевать\ntańczę, tańczysz, tańczy..."},
{q:"Как по-польски: читать книги",a:"czytać książki",hint:"I спр.",rule:"czytać książki = читать книги"},
{q:"Как по-польски: читать газеты",a:"czytać gazety",hint:"мн.ч.",rule:"czytać gazety = читать газеты"},
{q:"Как по-польски: смотреть телевизор",a:"oglądać telewizję",hint:"oglądać + B.",rule:"oglądać telewizję = смотреть ТВ"},
{q:"Как по-польски: встречаться с друзьями",a:"spotykać się z kolegami",hint:"z + Narz.",rule:"spotykać się z + Narzędnik:\nz kolegami, z przyjaciółmi"},
{q:"Как по-польски: делать фотографии",a:"robić zdjęcia",hint:"robić",rule:"robić zdjęcia = делать фото\nrobić zakupy = делать покупки"},
{q:"Как по-польски: ходить в кафе",a:"chodzić do kawiarni",hint:"do + Dop.",rule:"chodzić do + Dopełniacz:\ndo kawiarni, do kina, do teatru"},
{q:"Как по-польски: ходить в кино",a:"chodzić do kina",hint:"do + Dop.",rule:"kino → kina (Dopełniacz)"},
{q:"Как по-польски: ходить в театр",a:"chodzić do teatru",hint:"do + Dop.",rule:"teatr → teatru (Dopełniacz)"},
{q:"Как по-польски: ходить в ресторан",a:"chodzić do restauracji",hint:"do + Dop.",rule:"restauracja → restauracji (Dop.)"},
{q:"Как по-польски: путешествовать",a:"podróżować",hint:"-ować",rule:"podróżować po + Miej.:\npo Europie, po Polsce"},
{q:"Как по-польски: заниматься спортом",a:"uprawiać sport",hint:"uprawiać",rule:"uprawiać sport = заниматься спортом"},
{q:"Как по-польски: петь",a:"śpiewać",hint:"I спр.",rule:"śpiewać = петь\nśpiewam, śpiewasz, śpiewa..."},
{q:"Как по-польски: играть в футбол",a:"grać w piłkę nożną",hint:"grać w + B.",rule:"piłka nożna → piłkę nożną (Biernik)"},
// ===== PODRĘCZNIK Ćw.2: Выбор слов (все 15) =====
{q:"Ćw.2: Andrzej bardzo lubi ... sport.",a:"uprawiać",hint:"uprawiać sport",rule:"uprawiać sport = заниматься спортом"},
{q:"Ćw.2.1: Bardzo lubię grać w ... – na przykład w brydża.",a:"karty",hint:"grać w karty",rule:"grać w karty = играть в карты\nbrydż = бридж"},
{q:"Ćw.2.2: Czy lubicie ... muzyki klasycznej?",a:"słuchać",hint:"słuchać + Dop.",rule:"słuchać muzyki klasycznej"},
{q:"Ćw.2.3: On nie lubi ... do teatru.",a:"chodzić",hint:"chodzić do + Dop.",rule:"lubić + chodzić do = любить ходить в"},
{q:"Ćw.2.4: Mariusz i Agnieszka lubią ... książki kryminalne.",a:"czytać",hint:"читать",rule:"czytać książki kryminalne = читать детективы"},
{q:"Ćw.2.5: Czy lubisz ... w tenisa?",a:"grać",hint:"grać w + B.",rule:"grać w tenisa = играть в теннис"},
{q:"Ćw.2.6: Mój znajomy lubi czytać ..., szczególnie 'Gazetę Wyborczą'.",a:"gazety",hint:"газеты",rule:"szczególnie = особенно"},
{q:"Ćw.2.7: Czy ... chodzić do teatru? (ty)",a:"lubisz",hint:"ty → lubisz",rule:"lubić: lubię, lubisz, lubi, lubimy, lubicie, lubią"},
{q:"Ćw.2.8: On bardzo lubi ... w Parku Wodnym.",a:"pływać",hint:"водный парк",rule:"pływać = плавать\nPark Wodny = аквапарк"},
{q:"Ćw.2.9: Marta i Wojtek bardzo lubią ... na rowerze.",a:"jeździć",hint:"jeździć na rowerze",rule:"jeździć na rowerze = кататься на велосипеде"},
{q:"Ćw.2.10: Bardzo lubimy ... po Europie.",a:"podróżować",hint:"путешествовать",rule:"podróżować po Europie"},
{q:"Ćw.2.11: Moja przyjaciółka lubi ... na dyskotece.",a:"tańczyć",hint:"дискотека",rule:"tańczyć na dyskotece = танцевать на дискотеке"},
{q:"Ćw.2.12: Ona bardzo lubi ... zakupy.",a:"robić",hint:"robić zakupy",rule:"robić zakupy = делать покупки"},
{q:"Ćw.2.13: Beata i Adam lubią się ... z kolegami.",a:"spotykać",hint:"spotykać się",rule:"spotykać się z kolegami"},
{q:"Ćw.2.14: Madonna lubi ... .",a:"śpiewać",hint:"певица",rule:"śpiewać = петь"},
{q:"Ćw.2.15: One lubią słuchać ... rockowej.\n(muzyka / muzykę / muzyki)",a:"muzyki",hint:"słuchać + Dop.",rule:"słuchać + Dopełniacz:\nmuzyka → muzyki"},
// ===== PODRĘCZNIK Ćw.5a: 3 конструкции (6 пунктов) =====
{q:"3 способа говорить о хобби?\nlubić + ?, lubić + ?, interesować się + ?",a:"bezokolicznik / Biernik / Narzędnik",hint:"инф. / B. / N.",rule:"1. lubić + bezokolicznik: Lubię czytać.\n2. lubić + Biernik: Lubię literaturę.\n3. interesować się + Narz.: Interesuję się literaturą."},
{q:"Ćw.5a: Lubię uprawiać sport → lubię ... → interesuję się ...",a:"sport / sportem",hint:"B. / N.",rule:"sport (B.=M.) / sportem (N.)"},
{q:"Ćw.5a.1: Dorota i Renata lubią chodzić do kina → one lubią ... → interesują się ...",a:"kino / kinem",hint:"B. / N.",rule:"kino (B.) / kinem (N.)"},
{q:"Ćw.5a.2: Mój brat lubi czytać książki → on lubi ... → interesuje się ...",a:"literaturę / literaturą",hint:"B. / N.",rule:"literatura → literaturę (B.) / literaturą (N.)"},
{q:"Ćw.5a.3: Nasz kuzyn lubi śpiewać i grać na gitarze → on lubi ... → interesuje się ...",a:"muzykę / muzyką",hint:"B. / N.",rule:"muzyka → muzykę (B.) / muzyką (N.)"},
{q:"Ćw.5a.4: Pani Wojciechowska lubi robić zdjęcia → ona lubi ... → interesuje się ...",a:"fotografię / fotografią",hint:"B. / N.",rule:"fotografia → fotografię (B.) / fotografią (N.)"},
{q:"Ćw.5a.5: Lubimy podróżować po Polsce → lubimy ... → interesujemy się ...",a:"geografię / geografią",hint:"B. / N.",rule:"geografia → geografię (B.) / geografią (N.)"},
// ===== PODRĘCZNIK Ćw.10: Таблицы спряжений =====
{q:"mieszkać: (ja)..., (ty)..., (on)...",a:"mieszkam, mieszkasz, mieszka",hint:"-m, -sz",rule:"Koniugacja -m, -sz:\nmieszkam, mieszkasz, mieszka\nmieszkamy, mieszkacie, mieszkają"},
{q:"mieszkać: (my)..., (wy)..., (oni)...",a:"mieszkamy, mieszkacie, mieszkają",hint:"-my, -cie, -ją",rule:"mieszkać мн.:\nmieszkamy, mieszkacie, mieszkają"},
{q:"rozumieć: (ja)..., (on)..., (wy)...",a:"rozumiem, rozumie, rozumiecie",hint:"-m, -sz",rule:"rozumieć:\nrozumiem, rozumiesz, rozumie\nrozumiemy, rozumiecie, rozumieją"},
{q:"czytać: (ja)..., (my)..., (oni)...",a:"czytam, czytamy, czytają",hint:"-m, -sz",rule:"czytać:\nczytam, czytasz, czyta\nczytamy, czytacie, czytają"},
{q:"jeść: (ja)..., (ty)..., (on)...",a:"jem, jesz, je",hint:"неправ.",rule:"jeść:\njem, jesz, je\njemy, jecie, jedzą"},
{q:"jeść: (wy)..., (oni)...",a:"jecie, jedzą",hint:"неправ.",rule:"jeść мн.: jemy, jecie, jedzą"},
{q:"wiedzieć: (ja)..., (ty)..., (oni)...",a:"wiem, wiesz, wiedzą",hint:"неправ.",rule:"wiedzieć:\nwiem, wiesz, wie\nwiemy, wiecie, wiedzą"},
{q:"mówić: (ja)..., (on)..., (oni)...",a:"mówię, mówi, mówią",hint:"-ę, -isz",rule:"mówić:\nmówię, mówisz, mówi\nmówimy, mówicie, mówią"},
{q:"lubić: (ja)..., (ty)..., (oni)...",a:"lubię, lubisz, lubią",hint:"-ę, -isz",rule:"lubić:\nlubię, lubisz, lubi\nlubimy, lubicie, lubią"},
{q:"chodzić: (ja)..., (on)..., (my)..., (oni)...",a:"chodzę, chodzi, chodzimy, chodzą",hint:"-ę, -isz",rule:"chodzić:\nchodzę, chodzisz, chodzi\nchodzimy, chodzicie, chodzą"},
{q:"tańczyć: (ja)..., (on)..., (my)...",a:"tańczę, tańczy, tańczymy",hint:"-ę, -ysz",rule:"tańczyć:\ntańczę, tańczysz, tańczy\ntańczymy, tańczycie, tańczą"},
{q:"uczyć się: (ja)..., (ty)..., (wy)..., (oni)...",a:"uczę się, uczysz się, uczycie się, uczą się",hint:"-ę, -ysz",rule:"uczyć się:\nuczę się, uczysz się, uczy się\nuczymy się, uczycie się, uczą się"},
{q:"chcieć: (ja)..., (on)..., (wy)..., (oni)...",a:"chcę, chce, chcecie, chcą",hint:"-ę, -esz неправ.",rule:"chcieć:\nchcę, chcesz, chce\nchcemy, chcecie, chcą"},
{q:"pisać: (ja)..., (ty)..., (oni)...",a:"piszę, piszesz, piszą",hint:"-ę, -esz, s→sz",rule:"pisać:\npiszę, piszesz, pisze\npiszemy, piszecie, piszą"},
{q:"móc: (ja)..., (ty)..., (on)..., (oni)...",a:"mogę, możesz, może, mogą",hint:"-ę, -esz, g→ż",rule:"móc:\nmogę, możesz, może\nmożemy, możecie, mogą"},
{q:"studiować: (ja)..., (on)..., (wy)..., (oni)...",a:"studiuję, studiuje, studiujecie, studiują",hint:"-ować → -uj-",rule:"studiować:\nstudiuję, studiujesz, studiuje\nstudiujemy, studiujecie, studiują"},
{q:"pracować: (ja)..., (ty)..., (my)...",a:"pracuję, pracujesz, pracujemy",hint:"-ować → -uj-",rule:"pracować:\npracuję, pracujesz, pracuje\npracujemy, pracujecie, pracują"},
// ===== PODRĘCZNIK Ćw.12b: -ować (все 11) =====
{q:"Ćw.12b.1: Ten student często ... (mailować)",a:"mailuje",hint:"on -uje",rule:"mailować → mailuje"},
{q:"Ćw.12b.2: (my) ... językiem polskim (interesować się)",a:"interesujemy się",hint:"my -ujemy",rule:"interesować się + Narzędnik"},
{q:"Ćw.12b.3: (ja) ... czasowniki (koniugować)",a:"koniuguję",hint:"ja -uję",rule:"koniugować → koniuguję"},
{q:"Ćw.12b.4: Co pani ...? (studiować)",a:"studiuje",hint:"pani = 3 ед.",rule:"pani → 3 лицо: studiuje"},
{q:"Ćw.12b.5: Magda i Anna często ... po internecie (surfować)",a:"surfują",hint:"one -ują",rule:"surfować → surfują"},
{q:"Ćw.12b.6: Andrzej codziennie ... (telefonować)",a:"telefonuje",hint:"on -uje",rule:"telefonować → telefonuje"},
{q:"Ćw.12b.7: Wojtek ... dom (dekorować)",a:"dekoruje",hint:"on -uje",rule:"dekorować → dekoruje"},
{q:"Ćw.12b.8: Gdzie państwo ...? (pracować)",a:"pracują",hint:"państwo = oni",rule:"państwo → 3 мн.: pracują"},
{q:"Ćw.12b.9: Dlaczego zawsze (ty) ... z profesorem? (dyskutować)",a:"dyskutujesz",hint:"ty -ujesz",rule:"dyskutować → dyskutujesz"},
{q:"Ćw.12b.10: Czy często pan ... z rodziną? (podróżować)",a:"podróżuje",hint:"pan = 3 ед.",rule:"podróżować → podróżuje"},
{q:"Ćw.12b.11: Tadeusz zawsze wszystko ... (planować)",a:"planuje",hint:"on -uje",rule:"planować → planuje"},
// ===== PODRĘCZNIK Ćw.14: смешанные (все 11) =====
{q:"Ćw.14.1: Czy ... pan mówić wolniej? (móc)",a:"może",hint:"pan = 3 ед.",rule:"móc → może (pan)"},
{q:"Ćw.14.2: On często ... telewizję (oglądać)",a:"ogląda",hint:"on -a",rule:"oglądać → ogląda"},
{q:"Ćw.14.3: Marek nigdy nie ... muzyki (słuchać)",a:"słucha",hint:"on -a",rule:"słuchać → słucha + Dop."},
{q:"Ćw.14.4: Czy one często ... maile? (pisać)",a:"piszą",hint:"one -ą",rule:"pisać → piszą"},
{q:"Ćw.14.5: Codziennie (ja) ... do pracy (chodzić)",a:"chodzę",hint:"ja -ę",rule:"chodzić → chodzę"},
{q:"Ćw.14.6: (ja) ... dobrze mówić po polsku (chcieć)",a:"chcę",hint:"ja -ę",rule:"chcieć → chcę"},
{q:"Ćw.14.7: Zwykle wieczorem Ania ... książkę (czytać)",a:"czyta",hint:"ona -a",rule:"czytać → czyta"},
{q:"Ćw.14.8: Pan Kaczmarczyk ... artykuł (pisać)",a:"pisze",hint:"on -e",rule:"pisać → pisze"},
{q:"Ćw.14.9: Co pan ... studiować? (chcieć)",a:"chce",hint:"pan = 3 ед.",rule:"chcieć → chce"},
{q:"Ćw.14.10: Czy (wy) ... mówić wolniej? (móc)",a:"możecie",hint:"wy -ecie",rule:"móc → możecie"},
{q:"Ćw.14.11: Na lekcji (my) zawsze ... po polsku (mówić)",a:"mówimy",hint:"my -imy",rule:"mówić → mówimy"},
// ===== PODRĘCZNIK: Jak często? (все 7 наречий + примеры) =====
{q:"Расставь: rzadko, zawsze, często, nigdy nie, codziennie, od czasu do czasu, zwykle",a:"zawsze, codziennie, zwykle, często, od czasu do czasu, rzadko, nigdy nie",hint:"100% → 0%",rule:"zawsze = всегда\ncodziennie = каждый день\nzwykle = обычно\nczęsto = часто\nod czasu do czasu = время от времени\nrzadko = редко\nnigdy nie = никогда"},
{q:"... wieczorem czyta książki – lubi kryminały (всегда)",a:"Zawsze",hint:"100%",rule:"Zawsze = всегда"},
{q:"... gra na gitarze klasycznej (каждый день)",a:"Codziennie",hint:"co dzień",rule:"Codziennie = каждый день"},
{q:"... w weekend chodzi na basen (обычно)",a:"Zwykle",hint:"= обычно",rule:"Zwykle = обычно"},
{q:"... spotyka się z kolegami w kawiarni (часто)",a:"Często",hint:"~70%",rule:"Często = часто"},
{q:"... gra w tenisa (время от времени)",a:"Od czasu do czasu",hint:"иногда",rule:"Od czasu do czasu = время от времени"},
{q:"... chodzi do teatru, bo nie ma czasu (редко)",a:"Rzadko",hint:"мало",rule:"Rzadko = редко"},
{q:"... nie słucha muzyki dyskotekowej (никогда)",a:"Nigdy",hint:"0%",rule:"Nigdy nie = никогда не\nДвойное отрицание обязательно!"},
// ===== ZESZYT Ćw.1: Лишнее слово (все 5) =====
{q:"Zes.1.1: Лишнее: słuchać – śpiewać – tańczyć – spać",a:"spać",hint:"не хобби",rule:"słuchać, śpiewać, tańczyć = муз. хобби\nspać = спать"},
{q:"Zes.1.2: Лишнее: biegać – oglądać telewizję – pływać – jeździć na rowerze",a:"oglądać telewizję",hint:"не спорт",rule:"biegać, pływać, jeździć = спорт\noglądać TV = пассивное"},
{q:"Zes.1.3: Лишнее: grać na gitarze – podróżować samochodem – jeździć na rowerze – jeździć taksówką",a:"grać na gitarze",hint:"не транспорт",rule:"podróżować, jeździć = транспорт\ngrać na gitarze = музыка"},
{q:"Zes.1.4: Лишнее: książka – gazeta – zdjęcie – magazyn",a:"zdjęcie",hint:"не читать",rule:"książka, gazeta, magazyn = чтение\nzdjęcie = фото"},
{q:"Zes.1.5: Лишнее: telewizja – film – kawiarnia – kino",a:"kawiarnia",hint:"не экран",rule:"telewizja, film, kino = экран\nkawiarnia = кафе"},
// ===== ZESZYT Ćw.2: вставить слова (все 10) =====
{q:"Zes.2.1: Czy lubicie ... do teatru?",a:"chodzić",hint:"chodzić do",rule:"lubić chodzić do teatru"},
{q:"Zes.2.2: Lubię ... w tenisa.",a:"grać",hint:"grać w",rule:"grać w tenisa"},
{q:"Zes.2.3: Czy lubisz ... muzyki klasycznej?",a:"słuchać",hint:"słuchać + Dop.",rule:"słuchać muzyki klasycznej"},
{q:"Zes.2.4: Małgorzata lubi ... książki kryminalne.",a:"czytać",hint:"читать",rule:"czytać książki kryminalne"},
{q:"Zes.2.5: Mój znajomy lubi czytać ..., szczególnie 'Rzeczpospolitą'.",a:"gazety",hint:"газеты",rule:"czytać gazety"},
{q:"Zes.2.6: Lubię chodzić do ... – na przykład do Teatru Starego.",a:"teatru",hint:"do + Dop.",rule:"do teatru (Dopełniacz)"},
{q:"Zes.2.7: Magda i Agnieszka lubią uprawiać ... – lubią jeździć na ...",a:"sport / rowerze",hint:"sport, na rowerze",rule:"uprawiać sport\njeździć na rowerze"},
{q:"Zes.2.8: Mój przyjaciel lubi ... – na przykład walca.",a:"tańczyć",hint:"walc = вальс",rule:"tańczyć = танцевать"},
{q:"Zes.2.9: Barbara lubi ... z kolegami.",a:"spotykać się",hint:"spotykać się z",rule:"spotykać się z kolegami"},
{q:"Zes.2.10: Andrzej lubi ... telewizję.",a:"oglądać",hint:"смотреть ТВ",rule:"oglądać telewizję"},
// ===== ZESZYT Ćw.3: Антонимы (все 5) =====
{q:"Zes.3.1: ≠ Często uprawiam sport.",a:"Rzadko uprawiam sport.",hint:"часто ≠ редко",rule:"często ≠ rzadko"},
{q:"Zes.3.2: ≠ Zwykle w weekend słucham muzyki.",a:"Nigdy nie słucham muzyki w weekend.",hint:"обычно ≠ никогда",rule:"zwykle ≠ nigdy nie"},
{q:"Zes.3.3: ≠ Profesor zawsze mówi wolno.",a:"Profesor nigdy nie mówi wolno.",hint:"всегда ≠ никогда",rule:"zawsze ≠ nigdy nie"},
{q:"Zes.3.4: ≠ Andrzej rzadko dzwoni do koleżanki z liceum.",a:"Andrzej często dzwoni do koleżanki z liceum.",hint:"редко ≠ часто",rule:"rzadko ≠ często"},
{q:"Zes.3.5: ≠ Nigdy nie biegam w weekend.",a:"Zawsze biegam w weekend.",hint:"никогда ≠ всегда",rule:"nigdy nie ≠ zawsze"},
// ===== ZESZYT Ćw.4: Biernik / Narzędnik (все 12) =====
{q:"Zes.4.1: On interesuje się ... (francuski sport)",a:"francuskim sportem",hint:"Narz.",rule:"francuski → francuskim, sport → sportem"},
{q:"Zes.4.2: Bardzo lubię ... (niemiecka kuchnia)",a:"niemiecką kuchnię",hint:"Biernik",rule:"niemiecka → niemiecką, kuchnia → kuchnię"},
{q:"Zes.4.3: Ona lubi ... (wino i sałatka grecka)",a:"wino i sałatkę grecką",hint:"Biernik",rule:"wino (B.=M.), sałatka → sałatkę, grecka → grecką"},
{q:"Zes.4.4: Lubisz ...? (muzyka klasyczna)",a:"muzykę klasyczną",hint:"lubić + B.",rule:"muzyka → muzykę, klasyczna → klasyczną"},
{q:"Zes.4.5: Interesujesz się ...? (muzyka hiszpańska)",a:"muzyką hiszpańską",hint:"int. się + N.",rule:"muzyka → muzyką, hiszpańska → hiszpańską"},
{q:"Zes.4.6: Mam ... (interesująca książka)",a:"interesującą książkę",hint:"mieć + B.",rule:"interesująca → interesującą, książka → książkę"},
{q:"Zes.4.7: Czytam ... (kolorowy magazyn)",a:"kolorowy magazyn",hint:"B. муж.неод.=М.",rule:"Biernik муж. неодуш. = Mianownik"},
{q:"Zes.4.8: Oni czytają ... (aktualna gazeta)",a:"aktualną gazetę",hint:"B. жен.",rule:"aktualna → aktualną, gazeta → gazetę"},
{q:"Zes.4.9: Oni interesują się ... (literatura angielska)",a:"literaturą angielską",hint:"N. жен.",rule:"literatura → literaturą, angielska → angielską"},
{q:"Zes.4.10: Lubisz ...? (kawa)",a:"kawę",hint:"B. -a→-ę",rule:"kawa → kawę (Biernik)"},
{q:"Zes.4.11: Masz ...? (dobry samochód)",a:"dobry samochód",hint:"B. муж.неод.=М.",rule:"Biernik муж. неодуш. = Mianownik"},
{q:"Zes.4.12: Interesujesz się ...? (filozofia)",a:"filozofią",hint:"N. -ia→-ią",rule:"filozofia → filozofią (Narzędnik)"},
// ===== ZESZYT Ćw.5: выбрать слово (все 5) =====
{q:"Zes.5.1: Anna lubi czytać gazety – interesuje się ...\nOczywiście lubi też ... telewizję.",a:"polityką / oglądać",hint:"int.się + N. / lubić + inf.",rule:"interesuje się polityką\nlubi też oglądać telewizję"},
{q:"Zes.5.2: Mariusz lubi ... . Lubi ... czasopisma ekonomiczne.",a:"ekonomię / czytać",hint:"B. / inf.",rule:"lubi ekonomię (Biernik)\nlubi czytać (инфинитив)"},
{q:"Zes.5.3: Wojtek interesuje się ... hiszpańską. Lubi ... hiszpański.",a:"kulturą / język",hint:"N. / B.",rule:"interesuje się kulturą (N.)\nlubi język (B.)"},
{q:"Zes.5.4: Agnieszka bardzo lubi ... w tenisa – lubi ...",a:"grać / sport",hint:"inf. / B.",rule:"lubi grać (инф.)\nlubi sport (Biernik)"},
{q:"Zes.5.5: Katarzyna lubi ... na nartach. Interesuje się ...",a:"jeździć / sportem",hint:"inf. / N.",rule:"lubi jeździć (инф.)\ninteresuje się sportem (N.)"},
// ===== ZESZYT Ćw.6: предлоги (все 10) =====
{q:"Zes.6.1: Lubimy podróżować ... Europie.",a:"po",hint:"po + Miej.",rule:"podróżować po + Miej."},
{q:"Zes.6.2: Grażyna świetnie gra ... saksofonie.",a:"na",hint:"grać na (инстр.)",rule:"grać na + Miej."},
{q:"Zes.6.3: Andrzej rzadko spotyka się ... rodzicami.",a:"z",hint:"z + Narz.",rule:"spotykać się z + Narz."},
{q:"Zes.6.4: Czy twój ojciec lubi chodzić ... teatru?",a:"do",hint:"do + Dop.",rule:"chodzić do + Dop."},
{q:"Zes.6.5: Czy lubisz chodzić ... dyskotekę?",a:"na",hint:"na мероприятие",rule:"chodzić na + B.:\nna dyskotekę, na koncert, na basen"},
{q:"Zes.6.6: Moja matka świetnie gra ... gitarze.",a:"na",hint:"grać na (инстр.)",rule:"grać na gitarze"},
{q:"Zes.6.7: Często spotykam się ... kolegami.",a:"z",hint:"z + Narz.",rule:"spotykać się z kolegami"},
{q:"Zes.6.8: Często chodzimy ... restauracji.",a:"do",hint:"do + Dop.",rule:"chodzić do restauracji"},
{q:"Zes.6.9: Nie umiem grać ... karty.",a:"w",hint:"grać w (игра)",rule:"grać w + B.: w karty, w tenisa"},
{q:"Zes.6.10: Czy lubisz chodzić ... teatru?",a:"do",hint:"do + Dop.",rule:"chodzić do teatru"},
// ===== ZESZYT Ćw.7A: -ować (все 10) =====
{q:"Zes.7A.1: Dwa samoloty ... (lądować)",a:"lądują",hint:"oni -ują",rule:"lądować → lądują"},
{q:"Zes.7A.2: Marek ... samochód (parkować)",a:"parkuje",hint:"on -uje",rule:"parkować → parkuje"},
{q:"Zes.7A.3: Dwa samochody ... (parkować)",a:"parkują",hint:"oni -ują",rule:"parkować → parkują"},
{q:"Zes.7A.4: Co (ty) ...? (studiować)",a:"studiujesz",hint:"ty -ujesz",rule:"studiować → studiujesz"},
{q:"Zes.7A.5: Czym ona ...? (interesować się)",a:"interesuje się",hint:"ona -uje się",rule:"interesować się → interesuje się"},
{q:"Zes.7A.6: Gdzie (wy) ...? (pracować)",a:"pracujecie",hint:"wy -ujecie",rule:"pracować → pracujecie"},
{q:"Zes.7A.7: (my) ... w Bytomiu (pracować)",a:"pracujemy",hint:"my -ujemy",rule:"pracować → pracujemy"},
{q:"Zes.7A.8: Codziennie (my) ... w internecie (surfować)",a:"surfujemy",hint:"my -ujemy",rule:"surfować → surfujemy"},
{q:"Zes.7A.9: Maria rzadko ... (mailować)",a:"mailuje",hint:"ona -uje",rule:"mailować → mailuje"},
{q:"Zes.7A.10: (ja) ... historią (interesować się)",a:"interesuję się",hint:"ja -uję się",rule:"interesować się → interesuję się"},
// ===== ZESZYT Ćw.7B: -m, -sz (все 10) =====
{q:"Zes.7B.1: (ja) ... interesującą książkę (czytać)",a:"czytam",hint:"ja -am",rule:"czytać → czytam"},
{q:"Zes.7B.2: Jak często (ty) ... w restauracji? (jeść)",a:"jesz",hint:"неправ.",rule:"jeść → jesz (ty)"},
{q:"Zes.7B.3: On ... (pływać)",a:"pływa",hint:"on -a",rule:"pływać → pływa"},
{q:"Zes.7B.4: (my) ... muzyki (słuchać)",a:"słuchamy",hint:"my -amy",rule:"słuchać → słuchamy"},
{q:"Zes.7B.5: One pięknie ... (śpiewać)",a:"śpiewają",hint:"one -ają",rule:"śpiewać → śpiewają"},
{q:"Zes.7B.6: Czy (wy) ...? (biegać)",a:"biegacie",hint:"wy -acie",rule:"biegać → biegacie"},
{q:"Zes.7B.7: Oni ... w tenisa (grać)",a:"grają",hint:"oni -ają",rule:"grać → grają"},
{q:"Zes.7B.8: Czy (ty) ... na gitarze? (grać)",a:"grasz",hint:"ty -asz",rule:"grać → grasz"},
{q:"Zes.7B.9: Czy (wy) ... w piłkę nożną? (grać)",a:"gracie",hint:"wy -acie",rule:"grać → gracie"},
{q:"Zes.7B.10: Jak często (ty) ... telewizję? (oglądać)",a:"oglądasz",hint:"ty -asz",rule:"oglądać → oglądasz"},
// ===== ZESZYT Ćw.7C: -ę, -isz (все 10) =====
{q:"Zes.7C.1: Czy (ty) ... chodzić do kina? (lubić)",a:"lubisz",hint:"ty -isz",rule:"lubić → lubisz"},
{q:"Zes.7C.2: (ja) ... słabo po polsku (mówić)",a:"mówię",hint:"ja -ię",rule:"mówić → mówię"},
{q:"Zes.7C.3: Czy (wy) ... po rosyjsku? (mówić)",a:"mówicie",hint:"wy -icie",rule:"mówić → mówicie"},
{q:"Zes.7C.4: Oni ... pływać (lubić)",a:"lubią",hint:"oni -ią",rule:"lubić → lubią"},
{q:"Zes.7C.5: Jak często (wy) ... do kina? (chodzić)",a:"chodzicie",hint:"wy -icie",rule:"chodzić → chodzicie"},
{q:"Zes.7C.6: Dlaczego (ty) ... języka polskiego? (uczyć się)",a:"uczysz się",hint:"ty -ysz",rule:"uczyć się → uczysz się"},
{q:"Zes.7C.7: Co oni ... codziennie? (robić)",a:"robią",hint:"oni -ią",rule:"robić → robią"},
{q:"Zes.7C.8: Co (ty) ... w weekend? (robić)",a:"robisz",hint:"ty -isz",rule:"robić → robisz"},
{q:"Zes.7C.9: Czy one dobrze ...? (tańczyć)",a:"tańczą",hint:"one -ą",rule:"tańczyć → tańczą"},
{q:"Zes.7C.10: Oni ... chodzić do kina (lubić)",a:"lubią",hint:"oni -ią",rule:"lubić → lubią"},
// ===== ZESZYT Ćw.7D: -ę, -esz (все 10) =====
{q:"Zes.7D.1: Dziennikarz ... artykuł (pisać)",a:"pisze",hint:"on -e",rule:"pisać → pisze"},
{q:"Zes.7D.2: Czy (ty) często ... e-maile? (pisać)",a:"piszesz",hint:"ty -esz",rule:"pisać → piszesz"},
{q:"Zes.7D.3: Czy (ja) ... prosić o uwagę? (móc)",a:"mogę",hint:"ja -ę",rule:"móc → mogę"},
{q:"Zes.7D.4: Czy ... pan mówić wolniej? (móc)",a:"może",hint:"pan = 3 ед.",rule:"móc → może (pan)"},
{q:"Zes.7D.5: Co (ty) ... robić dzisiaj wieczorem? (chcieć)",a:"chcesz",hint:"ty -esz",rule:"chcieć → chcesz"},
{q:"Zes.7D.6: Marta ... pracować w Polsce (chcieć)",a:"chce",hint:"ona -e",rule:"chcieć → chce"},
{q:"Zes.7D.7: Anna i Dorota ... do 'Gazety Wyborczej' (pisać)",a:"piszą",hint:"one -ą",rule:"pisać → piszą"},
{q:"Zes.7D.8: One ... mieszkać w Polsce (chcieć)",a:"chcą",hint:"one -ą",rule:"chcieć → chcą"},
{q:"Zes.7D.9: Czy (wy) ... powtórzyć numer? (móc)",a:"możecie",hint:"wy -ecie",rule:"móc → możecie"},
{q:"Zes.7D.10: W poniedziałek (ja) ... test z polskiego (pisać)",a:"piszę",hint:"ja -ę",rule:"pisać → piszę"},
// ===== ZESZYT Ćw.8A: смешанные (все 15) =====
{q:"Zes.8A.1: (ja) ... artykuł (pisać)",a:"piszę",hint:"-ę, -esz",rule:"pisać → piszę"},
{q:"Zes.8A.2: One ... regularnie na kurs francuskiego (chodzić)",a:"chodzą",hint:"-ę, -isz",rule:"chodzić → chodzą"},
{q:"Zes.8A.3: Czy pan ... pracować we Wrocławiu? (chcieć)",a:"chce",hint:"pan = 3 ед.",rule:"chcieć → chce"},
{q:"Zes.8A.4: Czy (wy) ... sport? (lubić)",a:"lubicie",hint:"wy -icie",rule:"lubić → lubicie"},
{q:"Zes.8A.5: (ty) ... problem? (mieć)",a:"masz",hint:"ty -asz",rule:"mieć → masz"},
{q:"Zes.8A.6: Czy pani ... po niemiecku? (mówić)",a:"mówi",hint:"pani = 3 ед.",rule:"mówić → mówi"},
{q:"Zes.8A.7: Uczeń ... do szkoły (chodzić)",a:"chodzi",hint:"on -i",rule:"chodzić → chodzi"},
{q:"Zes.8A.8: Oni świetnie ... sambę (tańczyć)",a:"tańczą",hint:"oni -ą",rule:"tańczyć → tańczą"},
{q:"Zes.8A.9: Czy (ty) ... w Krakowie? (studiować)",a:"studiujesz",hint:"-ować → -ujesz",rule:"studiować → studiujesz"},
{q:"Zes.8A.10: Gdzie (ty) ...? (mieszkać)",a:"mieszkasz",hint:"ty -asz",rule:"mieszkać → mieszkasz"},
{q:"Zes.8A.11: (ja) ... języka polskiego (uczyć się)",a:"uczę się",hint:"ja -ę",rule:"uczyć się → uczę się"},
{q:"Zes.8A.12: Czy (wy) ... na kurs polskiego? (chodzić)",a:"chodzicie",hint:"wy -icie",rule:"chodzić → chodzicie"},
{q:"Zes.8A.13: Oni świetnie ... po polsku (mówić)",a:"mówią",hint:"oni -ią",rule:"mówić → mówią"},
{q:"Zes.8A.14: On ... książkę (pisać)",a:"pisze",hint:"on -e",rule:"pisać → pisze"},
{q:"Zes.8A.15: Anna ... europeistykę (studiować)",a:"studiuje",hint:"-uje",rule:"studiować → studiuje"},
// ===== ZESZYT Ćw.8B: смешанные (все 15) =====
{q:"Zes.8B.1: Oni ... na dyskotece (tańczyć)",a:"tańczą",hint:"oni -ą",rule:"tańczyć → tańczą"},
{q:"Zes.8B.2: (my) ... duży dom (mieć)",a:"mamy",hint:"my -amy",rule:"mieć → mamy"},
{q:"Zes.8B.3: Czy Paweł ... w Warszawie? (pracować)",a:"pracuje",hint:"-uje",rule:"pracować → pracuje"},
{q:"Zes.8B.4: Teraz (ja) nie ... słuchać muzyki (chcieć)",a:"chcę",hint:"ja -ę",rule:"chcieć → chcę"},
{q:"Zes.8B.5: Czy (wy) ... literaturą? (interesować się)",a:"interesujecie się",hint:"wy -ujecie",rule:"interesować się → interesujecie się"},
{q:"Zes.8B.6: Czy pan ... mówić trochę wolniej? (móc)",a:"może",hint:"pan = 3 ед.",rule:"móc → może"},
{q:"Zes.8B.7: Oni ... w pokoju (być)",a:"są",hint:"неправ.",rule:"być → są (oni)"},
{q:"Zes.8B.8: Czy (wy) ... po angielsku? (czytać)",a:"czytacie",hint:"wy -acie",rule:"czytać → czytacie"},
{q:"Zes.8B.9: Czy (ty) ... języka polskiego? (uczyć się)",a:"uczysz się",hint:"ty -ysz",rule:"uczyć się → uczysz się"},
{q:"Zes.8B.10: Wojtek i Ania ... zadanie domowe (robić)",a:"robią",hint:"oni -ią",rule:"robić → robią"},
{q:"Zes.8B.11: Czy (ty) ... dobrze język polski? (znać)",a:"znasz",hint:"ty -asz",rule:"znać → znasz"},
{q:"Zes.8B.12: (oni) ..., że to jest bez sensu (wiedzieć)",a:"wiedzą",hint:"неправ.",rule:"wiedzieć → wiedzą"},
{q:"Zes.8B.13: (ja) ..., ale nie ... (przepraszać / rozumieć)",a:"przepraszam / rozumiem",hint:"-m, -m",rule:"przepraszać → przepraszam\nrozumieć → rozumiem"},
{q:"Zes.8B.14: Czy (ty) ... mówić wolniej? (móc)",a:"możesz",hint:"ty -esz",rule:"móc → możesz"},
{q:"Zes.8B.15: (ja) ... studiować ekonomię (chcieć)",a:"chcę",hint:"ja -ę",rule:"chcieć → chcę"}
]}
];
